// fregitmenimclaude - Kelime Veritabanı
// Format: "FrWord|TrMeaning|FrSentence (TrSentence)"
// Bu dosyaya dışarıdan yeni satır ekleyip "Kelimeleri Güncelle" butonuna basın.

window.WORD_DATA = `Le père|Baba|Mon père est très travailleur. (Babam çok çalışkandır.)
La mère|Anne|Ma mère prépare le dîner. (Annem akşam yemeğini hazırlıyor.)
Le frère|Erkek kardeş|Mon frère joue au football. (Erkek kardeşim futbol oynuyor.)
La sœur|Kız kardeş|Ma sœur écoute de la musique. (Kız kardeşim müzik dinliyor.)
Le grand-père|Büyükbaba|Mon grand-père lit le journal. (Büyükbabam gazete okuyor.)
La grand-mère|Büyükanne|Ma grand-mère fait un gâteau. (Büyükanne bir pasta yapıyor.)
L'oncle|Amca / Dayı|Mon oncle habite à Paris. (Amcam Paris'te yaşıyor.)
La tante|Hala / Teyze|Ma tante est professeur. (Teyzem öğretmendir.)
Le cousin|Erkek kuzen|Mon cousin a dix ans. (Kuzenim on yaşında.)
La cousine|Kız kuzen|Ma cousine est très gentille. (Kuzenim çok naziktir.)
Le fils|Erkek oğul|Son fils va à l'école. (Onun oğlu okula gidiyor.)
La fille|Kız çocuk / Kız|C'est une fille intelligente. (O akıllı bir kız.)
Le bébé|Bebek|Le bébé pleure beaucoup. (Bebek çok ağlıyor.)
L'enfant|Çocuk|L'enfant joue dans le parc. (Çocuk parkta oynuyor.)
L'homme|Adam|Cet homme est très grand. (Bu adam çok uzun.)
La femme|Kadın|La femme porte une robe. (Kadın bir elbise giyiyor.)
Lundi|Pazartesi|Je travaille le lundi. (Pazartesi günü çalışıyorum.)
Mardi|Salı|Mardi, nous avons une réunion. (Salı günü bir toplantımız var.)
Mercredi|Çarşamba|Je vais au cinéma mercredi. (Çarşamba günü sinemaya gidiyorum.)
Jeudi|Perşembe|Il arrive jeudi matin. (O perşembe sabahı varıyor.)
Vendredi|Cuma|Vendredi est mon jour préféré. (Cuma en sevdiğim gündür.)
Samedi|Cumartesi|Nous faisons les courses samedi. (Cumartesi günü alışveriş yapıyoruz.)
Dimanche|Pazar|Dimanche, je me repose. (Pazar günü dinleniyorum.)
Janvier|Ocak|Il fait très froid en janvier. (Ocak ayında hava çok soğuktur.)
Février|Şubat|Mon anniversaire est en février. (Doğum günüm şubattadır.)
Mars|Mart|Le printemps commence en mars. (İlkbahar mart ayında başlar.)
Avril|Nisan|Il pleut beaucoup en avril. (Nisan ayında çok yağmur yağar.)
Le printemps|İlkbahar|Les fleurs poussent au printemps. (Çiçekler ilkbaharda büyür.)
L'été|Yaz|Nous allons à la plage en été. (Yazın plaja gideriz.)
L'automne|Sonbahar|Les feuilles tombent en automne. (Yapraklar sonbaharda düşer.)
L'hiver|Kış|J'aime la neige en hiver. (Kışın karı severim.)
La télévision|Televizyon|J'allume la télévision. (Televizyonu açıyorum.)
La radio|Radyo|J'écoute les nouvelles à la radio. (Radyoda haberleri dinliyorum.)
Le frigo|Buzdolabı|Le frigo est vide. (Buzdolabı boş.)
Le four|Fırın|Le gâteau est dans le four. (Pasta fırının içinde.)
L'assiette|Tabak|L'assiette est sur la table. (Tabak masanın üzerindedir.)
Le verre|Bardak / Cam|Je voudrais un verre d'eau. (Bir bardak su isterim.)
La fourchette|Çatal|Il mange avec une fourchette. (O bir çatalla yiyor.)
Le couteau|Bıçak|Ce couteau coupe bien. (Bu bıçak iyi kesiyor.)
La cuillère|Kaşık|Je prends une cuillère pour la soupe. (Çorba için bir kaşık alıyorum.)
Le rideau|Perde|Tire le rideau, s'il te plaît. (Lütfen perdeyi çek.)
Le tapis|Halı|Le tapis est doux. (Halı yumuşaktır.)
L'armoire|Dolap|Mes vêtements sont dans l'armoire. (Kıyafetlerim dolaptadır.)
La douche|Duş|Je prends une douche chaude. (Sıcak bir duş alıyorum.)
La serviette|Havlu|Où est ma serviette ? (Havlum nerede?)
Le savon|Sabun|Je me lave les mains avec du savon. (Ellerimi sabunla yıkıyorum.)
La route|Yol|La route est très longue. (Yol çok uzundur.)
Le pont|Köprü|Nous traversons le pont. (Köprüyü geçiyoruz.)
La place|Meydan|Il y a du monde sur la place. (Meydanda kalabalık var.)
Le bâtiment|Bina|C'est un grand bâtiment moderne. (Bu büyük ve modern bir bina.)
Le musée|Müze|Nous visitons le musée. (Müzeyi ziyaret ediyoruz.)
Le cinéma|Sinema|Le film commence au cinéma. (Film sinemada başlıyor.)
L'école|Okul|L'école finit à quatre heures. (Okul saat dörtte bitiyor.)
La banque|Banka|Je dois aller à la banque. (Bankaya gitmeliyim.)
La pharmacie|Eczane|La pharmacie est ouverte. (Eczane açıktır.)
L'aéroport|Havalimanı|L'avion atterrit à l'aéroport. (Uçak havalimanına iniyor.)
Le billet|Bilet|J'achète un billet de train. (Bir tren bileti alıyorum.)
Le passager|Yolcu|Le passager attend son vol. (Yolcu uçuşunu bekliyor.)
La valise|Bavul|Ma valise est prête. (Bavulum hazır.)
Le vol|Uçuş / Hırsızlık|Le vol est annulé. (Uçuş iptal edildi.)
Le t-shirt|Tişört|Il porte un t-shirt blanc. (O beyaz bir tişört giyiyor.)
La robe|Elbise|Sa robe est magnifique. (Onun elbisesi muhteşem.)
La jupe|Etek|Elle achète une jupe rouge. (O kırmızı bir etek satın alıyor.)
Le pull|Kazak|Mets un pull, il fait froid. (Bir kazak giy, hava soğuk.)
La veste|Ceket|C'est une belle veste en cuir. (Bu güzel bir deri ceket.)
Les chaussettes|Çoraplar|Où sont mes chaussettes ? (Çoraplarım nerede?)
Le chapeau|Şapka|Il porte un chapeau noir. (O siyah bir şapka takıyor.)
L'écharpe|Atkı|Je mets mon écharpe. (Atkımı takıyorum.)
Les gants|Eldivenler|J'ai besoin de gants en hiver. (Kışın eldivenlere ihtiyacım var.)
La ceinture|Kemer|Il achète une ceinture noire. (Siyah bir kemer satın alıyor.)
La montre|Saat (Kol saati)|Ma montre est cassée. (Saatim bozuk.)
Les lunettes|Gözlük|Il cherche ses lunettes. (Gözlüklerini arıyor.)
L'eau minérale|Maden suyu|Je préfère l'eau minérale. (Maden suyunu tercih ederim.)
Le jus|Meyve suyu|Un verre de jus d'orange, s'il vous plaît. (Bir bardak portakal suyu lütfen.)
Le thé|Çay|Nous buvons du thé noir. (Siyah çay içiyoruz.)
Le vin|Şarap|Le vin français est célèbre. (Fransız şarabı ünlüdür.)
La bière|Bira|Il commande une bière. (Bir bira sipariş ediyor.)
La soupe|Çorba|La soupe est délicieuse. (Çorba lezzetlidir.)
La salade|Salata|Je prépare une salade verte. (Yeşil bir salata hazırlıyorum.)
La pizza|Pizza|Nous mangeons une pizza ce soir. (Bu akşam pizza yiyoruz.)
Le gâteau|Pasta / Kek|C'est un gâteau au chocolat. (Bu çikolatalı bir pasta.)
Le chocolat|Çikolata|Les enfants aiment le chocolat. (Çocuklar çikolatayı sever.)
La glace|Dondurma|Je mange une glace à la vanille. (Vanilyalı dondurma yiyorum.)
Faim|Açlık|J'ai très faim. (Çok açım.)
Soif|Susuzluk|J'ai soif, donne-moi de l'eau. (Susadım, bana su ver.)
Délicieux|Lezzetli|Ce repas est délicieux. (Bu yemek lezzetli.)
Aimer|Sevmek|J'aime beaucoup ce film. (Bu filmi çok seviyorum.)
Détester|Nefret etmek|Je déteste la pluie. (Yağmurdan nefret ederim.)
Travailler|Çalışmak|Elle travaille dans un bureau. (O bir ofiste çalışıyor.)
Jouer|Oynamak|Les enfants jouent dehors. (Çocuklar dışarıda oynuyor.)
Aider|Yardım etmek|Je peux vous aider ? (Size yardım edebilir miyim?)
Changer|Değiştirmek|Je dois changer mes vêtements. (Kıyafetlerimi değiştirmeliyim.)
Commencer|Başlamak|Le cours commence à huit heures. (Ders saat sekizde başlıyor.)
Finir|Bitirmek|Je finis mon travail. (İşimi bitiriyorum.)
Choisir|Seçmek|Tu dois choisir une couleur. (Bir renk seçmelisin.)
Partir|Ayrılmak / Yola çıkmak|Nous partons demain matin. (Yarın sabah yola çıkıyoruz.)
Sortir|Çıkmak|Je veux sortir ce soir. (Bu gece dışarı çıkmak istiyorum.)
Attendre|Beklemek|J'attends le bus. (Otobüsü bekliyorum.)
Entendre|Duymak|Je n'entends rien. (Hiçbir şey duymuyorum.)
Répondre|Cevap vermek|Il ne répond pas au téléphone. (O telefona cevap vermiyor.)
Vendre|Satmak|Ils vendent leur maison. (Evlerini satıyorlar.)
Maintenant|Şimdi|Je dois partir maintenant. (Şimdi gitmeliyim.)
Bientôt|Yakında|À bientôt ! (Yakında görüşürüz!)
Tard|Geç|Il est trop tard. (Çok geç.)
L'ordinateur|Bilgisayar|L'ordinateur est sur le bureau. (Bilgisayar masanın üzerindedir.)
Le téléphone|Telefon|Mon téléphone sonne. (Telefonum çalıyor.)
L'écran|Ekran|L'écran de la télévision est grand. (Televizyonun ekranı büyüktür.)
Le clavier|Klavye|J'utilise un clavier sans fil. (Kablosuz bir klavye kullanıyorum.)
La souris|Fare (Bilgisayar)|La souris est à côté de l'ordinateur. (Fare bilgisayarın yanındadır.)
Le mot de passe|Şifre / Parola|J'ai oublié mon mot de passe. (Şifremi unuttum.)
La nature|Doğa|Il faut protéger la nature. (Doğayı korumak gerekir.)
La forêt|Orman|Nous nous promenons dans la forêt. (Ormanda yürüyüş yapıyoruz.)
La mer|Deniz|L'eau de la mer est froide. (Denizin suyu soğuk.)
Le soleil|Güneş|Le soleil brille aujourd'hui. (Bugün güneş parlıyor.)
L'étoile|Yıldız|Il y a beaucoup d'étoiles ce soir. (Bu akşam çok yıldız var.)
Le médecin|Doktor|Le médecin examine le patient. (Doktor hastayı muayene ediyor.)
L'infirmière|Hemşire|L'infirmière est très gentille. (Hemşire çok naziktir.)
L'avocat|Avukat|J'ai besoin de parler à mon avocat. (Avukatımla konuşmaya ihtiyacım var.)
Le professeur|Öğretmen|Le professeur explique la leçon. (Öğretmen dersi açıklıyor.)
Le policier|Polis|Le policier arrête la voiture. (Polis arabayı durduruyor.)
Le chien|Köpek|Le chien aboie fort ce soir. (Köpek bu akşam yüksek sesle havlıyor.)
Le chat|Kedi|Le chat dort sur le canapé. (Kedi kanepede uyuyor.)
L'oiseau|Kuş|L'oiseau chante tous les matins. (Kuş her sabah ötüyor.)
Le cheval|At|Il monte à cheval le week-end. (O hafta sonları ata biniyor.)
La vache|İnek|La vache donne du lait. (İnek süt verir.)
Le mouton|Koyun|Le mouton mange de l'herbe verte. (Koyun yeşil ot yiyor.)
La tête|Baş / Kafa|J'ai vraiment mal à la tête. (Gerçekten başım ağrıyor.)
Le bras|Kol|Il s'est cassé le bras hier. (O dün kolunu kırdı.)
La main|El|Lave-toi les mains avant le repas. (Yemekten önce ellerini yıka.)
La jambe|Bacak|Ma jambe me fait mal depuis hier. (Bacağım dünden beri ağrıyor.)
Le pied|Ayak|J'ai froid aux pieds en hiver. (Kışın ayaklarım üşüyor.)
L'œil|Göz|Il a un œil bleu et un œil vert. (Onun bir mavi, bir yeşil gözü var.)
Le nez|Burun|Mon nez coule à cause du rhume. (Nezle yüzünden burnum akıyor.)
La bouche|Ağız|Ferme la bouche quand tu manges. (Yemek yerken ağzını kapat.)
Le dos|Sırt|Mon dos est très douloureux ce matin. (Bu sabah sırtım çok ağrılı.)
Le ventre|Karın / Mide|J'ai mal au ventre, je dois m'allonger. (Karnım ağrıyor, uzanmalıyım.)
Rouge|Kırmızı|La pomme est très rouge et sucrée. (Elma çok kırmızı ve tatlı.)
Bleu|Mavi|Le ciel est bleu, sans aucun nuage. (Gökyüzü mavi, hiç bulut yok.)
Vert|Yeşil|L'herbe est plus verte au printemps. (Çimen ilkbaharda daha yeşildir.)
Jaune|Sarı|Le soleil est jaune et brillant. (Güneş sarı ve parlaktır.)
Noir|Siyah|Le chat noir me regarde fixement. (Siyah kedi bana dik dik bakıyor.)
Blanc|Beyaz|La neige est toute blanche. (Kar bembeyazdır.)
Gris|Gri|Le nuage est gris, il va pleuvoir. (Bulut gri, yağmur yağacak.)
Marron|Kahverengi|Ses yeux sont marron clair. (Gözleri açık kahverengi.)
Grand|Büyük / Uzun|C'est un très grand bâtiment. (Bu çok büyük bir bina.)
Petit|Küçük|Le petit garçon pleure dans la rue. (Küçük çocuk sokakta ağlıyor.)
Beau|Güzel / Yakışıklı|C'est un beau paysage d'automne. (Bu güzel bir sonbahar manzarası.)
Laid|Çirkin|Ce canard est particulièrement laid. (Bu ördek özellikle çirkin.)
Fort|Güçlü|Il est très fort pour soulever ça. (Bunu kaldıracak kadar çok güçlü.)
Faible|Zayıf / Güçsüz|Je me sens faible après la maladie. (Hastalıktan sonra güçsüz hissediyorum.)
Rapide|Hızlı|Ce nouveau train est très rapide. (Bu yeni tren çok hızlıdır.)
Lent|Yavaş|La tortue est un animal très lent. (Kaplumbağa çok yavaş bir hayvandır.)
Propre|Temiz|La chambre est propre et bien rangée. (Oda temiz ve düzenli.)
Sale|Kirli|Mes vêtements sont sales après le match. (Maçtan sonra kıyafetlerim kirli.)
Manger|Yemek yemek|Je veux manger une pomme maintenant. (Şimdi bir elma yemek istiyorum.)
Boire|İçmek|Il faut boire beaucoup d'eau chaque jour. (Her gün çok su içmek gerekir.)
Dormir|Uyumak|Je vais dormir tôt ce soir. (Bu akşam erken uyuyacağım.)
Parler|Konuşmak|Il parle trop vite pour moi. (O benim için çok hızlı konuşuyor.)
Écouter|Dinlemek|J'écoute la radio dans la voiture. (Arabada radyoyu dinlerim.)
Regarder|Bakmak / İzlemek|Regarde ce beau tableau sur le mur. (Duvardaki şu güzel tabloya bak.)
Voir|Görmek|Je ne vois rien dans le noir absolu. (Zifiri karanlıkta hiçbir şey görmüyorum.)
Courir|Koşmak|Il court chaque matin dans le grand parc. (Her sabah büyük parkta koşuyor.)
Marcher|Yürümek|Nous marchons ensemble vers le centre-ville. (Birlikte şehir merkezine yürüyoruz.)
Acheter|Satın almak|Je vais acheter du pain frais à la boulangerie. (Fırından taze ekmek alacağım.)
Payer|Ödemek|Je vais payer l'addition par carte de crédit. (Hesabı kredi kartıyla ödeyeceğim.)
Le vent|Rüzgar|Le vent souffle très fort aujourd'hui. (Rüzgar bugün çok sert esiyor.)
La pluie|Yağmur|La pluie tombe sans arrêt depuis hier. (Yağmur dünden beri durmadan yağıyor.)
La neige|Kar|La neige couvre toute la montagne. (Kar bütün dağı kaplıyor.)
La montagne|Dağ|Nous allons à la montagne pour faire du ski. (Kayak yapmak için dağa gidiyoruz.)
La rivière|Nehir|La rivière est très profonde ici. (Nehir burada çok derindir.)
L'arbre|Ağaç|Cet arbre au fond du jardin est très vieux. (Bahçenin sonundaki bu ağaç çok yaşlıdır.)
La fleur|Çiçek|Cette fleur rouge sent incroyablement bon. (Bu kırmızı çiçek inanılmaz güzel kokuyor.)
Le train|Tren|Le train pour Paris part à l'heure exacte. (Paris treni tam vaktinde kalkıyor.)
La voiture|Araba|Ma voiture est en panne sur l'autoroute. (Arabam otoyolda bozuldu.)
Le bus|Otobüs|Prends le bus numéro cinq pour y aller. (Oraya gitmek için beş numaralı otobüse bin.)
Le vélo|Bisiklet|J'aime faire du vélo dans la forêt. (Ormanda bisiklete binmeyi severim.)
Le bateau|Gemi / Tekne|Le bateau navigue tranquillement sur la mer. (Gemi denizde sakince seyrediyor.)
La station|İstasyon / Durak|Excusez-moi, où est la station de métro ? (Afedersiniz, metro istasyonu nerede?)
Le canapé|Kanepe|Le canapé gris du salon est très confortable. (Salondaki gri kanepe çok rahat.)
Le lit|Yatak|Le lit est défait, tu dois le faire. (Yatak dağınık, onu toplamalısın.)
La chaise|Sandalye|Prends une chaise et assieds-toi avec nous. (Bir sandalye al ve bizimle otur.)
La table|Masa|Le dîner est déjà servi sur la table. (Akşam yemeği masada çoktan servis edildi.)
La porte|Kapı|Ouvre la porte, s'il te plaît, il fait chaud. (Lütfen kapıyı aç, hava sıcak.)
La fenêtre|Pencere|Ferme la fenêtre, il fait très froid dehors. (Pencereyi kapat, dışarısı çok soğuk.)
La clé|Anahtar|J'ai perdu la clé de la maison ce matin. (Evin anahtarını bu sabah kaybettim.)
Le miroir|Ayna|Elle se regarde longtemps dans le miroir. (O aynada uzun uzun kendine bakıyor.)
Le boulanger|Fırıncı|Le boulanger prépare du bon pain croustillant. (Fırıncı güzel çıtır ekmek hazırlar.)
Le boucher|Kasap|Je vais chez le boucher pour acheter de la viande. (Et almak için kasaba gidiyorum.)
L'acteur|Aktör / Oyuncu|C'est un acteur très connu dans le monde entier. (O dünya çapında çok bilinen bir aktördür.)
Le chanteur|Şarkıcı|Ce chanteur a vraiment une belle voix. (Bu şarkıcının gerçekten güzel bir sesi var.)
L'ami|Arkadaş (Erkek)|C'est mon meilleur ami depuis l'enfance. (O çocukluktan beri en iyi arkadaşım.)
L'amie|Arkadaş (Kadın)|Mon amie habite actuellement à Lyon. (Arkadaşım şu anda Lyon'da yaşıyor.)
Le voisin|Komşu (Erkek)|Notre voisin du dessus est très bruyant. (Üst kat komşumuz çok gürültücü.)
La voisine|Komşu (Kadın)|La voisine a un chien adorable et calme. (Kadın komşunun sevimli ve sakin bir köpeği var.)
Le fromage|Peynir|La France est très célèbre pour son délicieux fromage. (Fransa lezzetli peyniriyle çok ünlüdür.)
Le poulet|Tavuk|Nous mangeons du poulet rôti ce soir. (Bu akşam fırında tavuk yiyoruz.)
Le poisson|Balık|Le poisson du marché est toujours frais. (Pazardaki balık her zaman tazedir.)
La viande|Et|Je ne mange pas beaucoup de viande rouge. (Çok fazla kırmızı et yemiyorum.)
Le pain|Ekmek|Achetons du pain frais pour le petit-déjeuner. (Kahvaltı için taze ekmek alalım.)
Le beurre|Tereyağı|Passe-moi le beurre, s'il te plaît. (Lütfen bana tereyağını uzat.)
Le sel|Tuz|La soupe de légumes manque un peu de sel. (Sebze çorbasının tuzu biraz eksik.)
Le sucre|Şeker|Je bois mon café sans aucun sucre. (Kahvemi hiç şekersiz içiyorum.)`;
Le trottoir|Kaldırım|Il est interdit de se garer sur le trottoir. (Kaldırıma park etmek yasaktır.)
Le feu rouge|Kırmızı ışık|Tu dois t'arrêter au feu rouge. (Kırmızı ışıkta durmalısın.)
Le carrefour|Kavşak|Tournez à gauche au prochain carrefour. (Bir sonraki kavşakta sola dönün.)
La ruelle|Sokak / Dar sokak|Cette ruelle est très sombre la nuit. (Bu dar sokak geceleri çok karanlık.)
La banlieue|Banliyö / Kenar mahalle|Ils habitent dans la banlieue de Paris. (Paris'in banliyösünde yaşıyorlar.)
Le plafond|Tavan|Le plafond de cette chambre est très haut. (Bu odanın tavanı çok yüksek.)
Le plancher|Zemin / Döşeme|Le plancher en bois grince. (Ahşap zemin gıcırdıyor.)
L'escalier|Merdiven|Fais attention en descendant l'escalier. (Merdivenden inerken dikkat et.)
Le balcon|Balkon|Je bois mon café sur le balcon. (Kahvemi balkonda içiyorum.)
La serrure|Kilit|La serrure de cette porte est cassée. (Bu kapının kilidi kırık.)
Le bureau|Ofis / Masa|Je suis au bureau jusqu'à 18h. (Saat 18'e kadar ofisteyim.)
La réunion|Toplantı|La réunion a été annulée. (Toplantı iptal edildi.)
Le patron|Patron|Mon patron est très exigeant. (Patronum çok talepkardır.)
Le collègue|Meslektaş / İş arkadaşı|Mes collègues sont très sympathiques. (İş arkadaşlarım çok cana yakın.)
L'entreprise|Şirket|Cette entreprise embauche de nouveaux ingénieurs. (Bu şirket yeni mühendisler işe alıyor.)
Le sable|Kum|Les enfants jouent dans le sable. (Çocuklar kumda oynuyor.)
La vague|Dalga|Les vagues sont très hautes aujourd'hui. (Bugün dalgalar çok yüksek.)
La pierre|Taş|Il a jeté une pierre dans le lac. (Göle bir taş attı.)
La poussière|Toz|Il y a beaucoup de poussière ici. (Burada çok toz var.)
L'ombre|Gölge|Reposons-nous à l'ombre de cet arbre. (Bu ağacın gölgesinde dinlenelim.)
Le fichier|Dosya (Bilgisayar)|N'oublie pas de sauvegarder le fichier. (Dosyayı kaydetmeyi unutma.)
Le mot de passe|Şifre / Parola|Mon mot de passe est très sécurisé. (Şifrem çok güvenlidir.)
Le chargeur|Şarj aleti|As-tu un chargeur de téléphone ? (Telefon şarj aletin var mı?)
L'écran|Ekran|L'écran de mon ordinateur est sale. (Bilgisayarımın ekranı kirli.)
Les écouteurs|Kulaklık|Je mets mes écouteurs pour écouter de la musique. (Müzik dinlemek için kulaklığımı takıyorum.)
Apprendre|Öğrenmek|J'apprends le français tous les jours. (Her gün Fransızca öğreniyorum.)
Comprendre|Anlamak|Je ne comprends pas cette phrase. (Bu cümleyi anlamıyorum.)
Oublier|Unutmak|J'ai oublié mes clés à la maison. (Anahtarlarımı evde unuttum.)
Se souvenir|Hatırlamak|Je me souviens de ce jour-là. (O günü hatırlıyorum.)
Espérer|Ummak / Ümit etmek|J'espère que tu iras mieux demain. (Umarım yarın daha iyi olursun.)
Réfléchir|Düşünmek / Kafa yormak|Je dois réfléchir avant de décider. (Karar vermeden önce düşünmeliyim.)
Gagner|Kazanmak|Notre équipe a gagné le match. (Takımımız maçı kazandı.)
Perdre|Kaybetmek|J'ai perdu mon portefeuille dans le bus. (Cüzdanımı otobüste kaybettim.)
Lourd|Ağır|Cette valise est trop lourde pour moi. (Bu bavul benim için çok ağır.)
Léger|Hafif|C'est un ordinateur très léger. (Bu çok hafif bir bilgisayar.)
Plein|Dolu|Le verre est plein d'eau. (Bardak suyla dolu.)
Vide|Boş|La rue est complètement vide ce soir. (Bu akşam sokak tamamen boş.)
Dangereux|Tehlikeli|Il est dangereux de nager ici. (Burada yüzmek tehlikelidir.)
Sécurisé|Güvenli|Ce quartier est très sécurisé. (Bu mahalle çok güvenli.)
Difficile|Zor|L'examen de mathématiques était très difficile. (Matematik sınavı çok zordu.)
Facile|Kolay|C'est une question très facile. (Bu çok kolay bir soru.)
Toujours|Her zaman|Il est toujours en retard. (O her zaman geç kalır.)
Jamais|Asla / Hiç|Je ne bois jamais de café le soir. (Akşamları asla kahve içmem.)
Parfois|Bazen|Parfois, je préfère rester seul. (Bazen yalnız kalmayı tercih ederim.)
Soudain|Aniden|Soudain, la lumière s'est éteinte. (Aniden ışık söndü.)
D'abord|Önce / İlk olarak|D'abord, nous devons trouver un hôtel. (Öncelikle bir otel bulmalıyız.)
Ensuite|Sonra / Daha sonra|Nous allons manger, et ensuite nous sortirons. (Yemek yiyeceğiz ve sonra çıkacağız.)
L'autoroute|Otoyol|Il y a beaucoup de trafic sur l'autoroute. (Otoyolda çok trafik var.)
Le vol|Uçuş|Mon vol a été annulé ce matin. (Uçuşum bu sabah iptal edildi.)
Le billet|Bilet|J'ai acheté un billet aller-retour pour Lyon. (Lyon'a gidiş-dönüş bileti aldım.)
La valise|Bavul|Ma valise est trop lourde pour moi. (Bavulum benim için çok ağır.)
Le passager|Yolcu|Le passager dort tranquillement dans l'avion. (Yolcu uçakta sakince uyuyor.)
La fourchette|Çatal|Je n'ai pas de fourchette pour manger ma salade. (Salatamı yemek için çatalım yok.)
La cuillère|Kaşık|Il boit sa soupe chaude avec une cuillère. (Sıcak çorbasını bir kaşıkla içiyor.)
Le couteau|Bıçak|Fais attention, ce couteau coupe très bien. (Dikkat et, bu bıçak çok iyi kesiyor.)
L'assiette|Tabak|J'ai cassé une assiette par accident ce matin. (Bu sabah kazara bir tabak kırdım.)
La poêle|Tava|Fais cuire les œufs dans la poêle, s'il te plaît. (Yumurtaları tavada pişir, lütfen.)
Le champignon|Mantar|J'adore manger la pizza aux champignons. (Mantarlı pizza yemeye bayılırım.)
L'oignon|Soğan|Couper des oignons me fait toujours pleurer. (Soğan doğramak beni her zaman ağlatır.)
L'ail|Sarımsak|Il y a trop d'ail dans cette sauce tomate. (Bu domates sosunda çok fazla sarımsak var.)
Heureux|Mutlu|Ils sont très heureux ensemble depuis des années. (Yıllardır birlikte çok mutlular.)
Triste|Üzgün|Elle est triste parce que son chien est malade. (Köpeği hasta olduğu için üzgün.)
Colérique|Sinirli / Öfkeli|Mon voisin est un homme très colérique. (Komşum çok öfkeli bir adamdır.)
Paresseux|Tembel|Mon chat est vraiment paresseux le dimanche. (Kedim pazar günleri gerçekten tembeldir.)
Travailleur|Çalışkan|C'est un étudiant très travailleur et intelligent. (O çok çalışkan ve zeki bir öğrencidir.)
Généreux|Cömert|Il est toujours généreux avec tous ses amis. (Bütün arkadaşlarına karşı her zaman cömerttir.)
Égoïste|Bencil|Ne sois pas si égoïste avec ta famille ! (Ailene karşı bu kadar bencil olma!)
Se réveiller|Uyanmak|Je me réveille à six heures tous les matins. (Her sabah saat altıda uyanırım.)
Se doucher|Duş almak|Je me douche immédiatement après le sport. (Spordan hemen sonra duş alırım.)
S'habiller|Giyinmek|Elle s'habille rapidement pour aller au travail. (İşe gitmek için hızlıca giyinir.)
Se brosser|Fırçalamak|N'oublie pas de te brosser les dents ce soir. (Bu akşam dişlerini fırçalamayı unutma.)
Se reposer|Dinlenmek|Je dois me reposer un peu après ce long voyage. (Bu uzun yolculuktan sonra biraz dinlenmeliyim.)
Se coucher|Yatmak / Uyumaya gitmek|Il se couche très tard le week-end. (Hafta sonları çok geç yatar.)
L'étoile|Yıldız|Il y a beaucoup d'étoiles dans le ciel ce soir. (Bu gece gökyüzünde çok yıldız var.)
La lune|Ay|La lune est pleine et brillante aujourd'hui. (Bugün ay dolunay ve parlak.)
Le nuage|Bulut|Les nuages sont gris, il va sûrement pleuvoir. (Bulutlar gri, kesinlikle yağmur yağacak.)
Le brouillard|Sis|Conduis prudemment à cause du brouillard épais. (Yoğun sis yüzünden dikkatli sür.)
L'orage|Fırtına / Gök gürültülü sağanak|J'ai très peur de l'orage depuis mon enfance. (Çocukluğumdan beri fırtınadan çok korkarım.)
L'arc-en-ciel|Gökkuşağı|Regarde ce bel arc-en-ciel après la pluie ! (Yağmurdan sonraki şu güzel gökkuşağına bak!)
La chemise|Gömlek|Il porte une chemise blanche pour sa réunion. (Toplantısı için beyaz bir gömlek giyiyor.)
Le pantalon|Pantolon|Ce pantalon noir est trop grand pour moi. (Bu siyah pantolon benim için çok büyük.)
La chaussure|Ayakkabı|Mes nouvelles chaussures sont très confortables. (Yeni ayakkabılarım çok rahat.)
La veste|Ceket|Prends ta veste, il fait vraiment froid dehors. (Ceketini al, dışarısı gerçekten soğuk.)
Le manteau|Mont / Palto|J'ai besoin d'un nouveau manteau pour l'hiver. (Kış için yeni bir paltoya ihtiyacım var.)
Le magasin|Mağaza|Ce magasin de vêtements ferme à vingt heures. (Bu giyim mağazası saat yirmide kapanır.)
La caisse|Kasa|Vous pouvez payer vos achats à la caisse. (Alışverişinizi kasada ödeyebilirsiniz.)
Cher|Pahalı|Cette robe rouge est beaucoup trop chère. (Bu kırmızı elbise çok fazla pahalı.)
Bon marché|Ucuz|J'ai trouvé un billet d'avion bon marché pour Paris. (Paris için ucuz bir uçak bileti buldum.)
Chercher|Aramak|Je cherche mes clés depuis dix minutes. (On dakikadır anahtarlarımı arıyorum.)
Trouver|Bulmak|J'ai enfin trouvé mon téléphone sous le canapé. (Sonunda telefonumu kanepenin altında buldum.)
Donner|Vermek|Peux-tu me donner ton numéro de téléphone ? (Bana telefon numaranı verebilir misin?)
Prendre|Almak|Je vais prendre un café noir, s'il vous plaît. (Bir sade kahve alacağım, lütfen.)
Aider|Yardım etmek|Il m'aide toujours avec mes devoirs de français. (Fransızca ödevlerimde bana her zaman yardım eder.)
Changer|Değiştirmek|Nous devons changer de train à la prochaine station. (Bir sonraki istasyonda tren değiştirmeliyiz.)
Hier|Dün|Je suis allé au cinéma hier avec mes amis. (Dün arkadaşlarımla sinemaya gittim.)
Aujourd'hui|Bugün|Il fait très beau aujourd'hui, allons nous promener. (Bugün hava çok güzel, yürüyüşe çıkalım.)
Demain|Yarın|Nous partirons en vacances demain matin. (Yarın sabah tatile çıkacağız.)
Le matin|Sabah|Je bois toujours du café le matin. (Sabahları her zaman kahve içerim.)
L'après-midi|Öğleden sonra|J'ai une réunion importante cet après-midi. (Bu öğleden sonra önemli bir toplantım var.)
Le soir|Akşam|Je lis un bon livre le soir avant de dormir. (Uyumadan önce akşamları iyi bir kitap okurum.)
La nuit|Gece|Il fait complètement noir pendant la nuit. (Gece boyunca hava tamamen karanlıktır.)
Chaud|Sıcak|Attention, ce thé est beaucoup trop chaud ! (Dikkat et, bu çay çok fazla sıcak!)
Froid|Soğuk|L'eau de la mer est très froide en hiver. (Kışın denizin suyu çok soğuktur.)
Nouveau|Yeni|J'ai acheté un nouvel ordinateur pour mon travail. (İşim için yeni bir bilgisayar aldım.)
Ancien|Eski|C'est un très ancien bâtiment historique. (Bu çok eski, tarihi bir bina.)
Jeune|Genç|Mon petit frère est encore très jeune. (Küçük kardeşim hala çok genç.)
Vieux|Yaşlı|Ce vieil homme est mon grand-père paternel. (Bu yaşlı adam benim baba tarafından büyükbabamdır.)
Riche|Zengin|Il est devenu riche grâce à son entreprise. (Şirketi sayesinde zengin oldu.)
Pauvre|Fakir|Il faut toujours aider les personnes pauvres. (Fakir insanlara her zaman yardım etmek gerekir.)
Le cœur|Kalp|Le cœur pompe le sang dans tout le corps. (Kalp, kanı tüm vücuda pompalar.)
L'hôpital|Hastane|Il travaille à l'hôpital comme infirmier. (Hastanede hemşire olarak çalışıyor.)
La pharmacie|Eczane|La pharmacie de garde est ouverte toute la nuit. (Nöbetçi eczane bütün gece açık.)
L'ingénieur|Mühendis|L'ingénieur dessine les plans du nouveau pont. (Mühendis yeni köprünün planlarını çiziyor.)
Le juge|Hakim|Le juge prendra sa décision finale demain. (Hakim son kararını yarın verecek.)
Le pompier|İtfaiyeci|Le pompier a courageusement sauvé le chat de l'arbre. (İtfaiyeci cesurca kediyi ağaçtan kurtardı.)
Le pilote|Pilot|Le pilote annonce le départ imminent de l'avion. (Pilot uçağın birazdan kalkacağını anons ediyor.)
Le métro|Metro|Je prends le métro tous les jours pour aller au travail. (İşe gitmek için her gün metroyu kullanıyorum.)
L'avion|Uçak|L'avion vole tranquillement au-dessus des nuages. (Uçak bulutların üzerinde sakince uçuyor.)
La gare|Tren istasyonu|La gare est située en plein centre-ville. (Tren istasyonu tam şehir merkezinde yer alıyor.)
Le stylo|Kalem|As-tu un stylo à me prêter pour signer ça ? (Bunu imzalamam için bana ödünç verecek bir kalemin var mı?)
Le livre|Kitap|Ce livre raconte une histoire fascinante. (Bu kitap büyüleyici bir hikaye anlatıyor.)
Lire|Okumak|J'aime lire des romans d'aventure pendant mon temps libre. (Boş zamanlarımda macera romanları okumayı severim.)
Écrire|Yazmak|Il écrit une longue lettre à son ami d'enfance. (Çocukluk arkadaşına uzun bir mektup yazıyor.)
Ouvrir|Açmak|Pouvez-vous ouvrir la fenêtre, s'il vous plaît ? (Pencereyi açabilir misiniz, lütfen?)
Fermer|Kapatmak|N'oublie pas de fermer la porte en sortant. (Çıkarken kapıyı kapatmayı unutma.)
Pleurer|Ağlamak|Le bébé commence à pleurer parce qu'il a faim. (Bebek aç olduğu için ağlamaya başlıyor.)
Rire|Gülmek|Cette blague me fait toujours rire aux éclats. (Bu şaka beni her zaman kahkahalarla güldürür.)
Sourire|Gülümsemek|Elle a l'habitude de sourire aux inconnus. (O, yabancılara gülümseme alışkanlığına sahiptir.)
Demander|Sormak / İstemek|Je dois demander l'heure à quelqu'un dans la rue. (Sokakta birine saati sormalıyım.)
Répondre|Cevap vermek|Il n'a pas voulu répondre à ma question personnelle. (Benim kişisel soruma cevap vermek istemedi.)
Savoir|Bilmek|Je ne sais pas du tout comment faire ça. (Bunu nasıl yapacağımı hiç bilmiyorum.)
Connaître|Tanımak / Bilmek (Bir yeri/kişiyi)|Connaissez-vous ce célèbre écrivain français ? (Bu ünlü Fransız yazarı tanıyor musunuz?)
Attendre|Beklemek|J'attends le bus depuis plus de vingt minutes. (Yirmi dakikadan fazladır otobüsü bekliyorum.)
Vivre|Yaşamak|Ils veulent vivre à la campagne, loin du bruit. (Gürültüden uzak, kırsalda yaşamak istiyorlar.)
