// fregitmenimclaude - Kelime Veritabanı
// Format: "FrWord|TrMeaning|FrSentence (TrSentence)"
// Bu dosyaya dışarıdan yeni satır ekleyip "Kelimeleri Güncelle" butonuna basın.

window.WORD_DATA = `Le père|Baba|Mon père est très travailleur. (Babam çok çalışkandır.)
La mère|Anne|Ma mère prépare le dîner. (Annem akşam yemeğini hazırlıyor.)
Le frère|Erkek kardeş|Mon frère joue au football. (Erkek kardeşim futbol oynuyor.)
La sœur|Kız kardeş|Ma sœur écoute de la musique. (Kız kardeşim müzik dinliyor.)
Le grand-père|Büyükbaba|Mon grand-père lit le journal. (Büyükbabam gazete okuyor.)
La grand-mère|Büyükanne|Ma grand-mère fait un gâteau. (Büyükanne bir pasta yapıyor.)
L'oncle|Amca / Dayı|Mon oncle habite à Paris. (Amcam Paris'te yaşıyor.)
La tante|Hala / Teyze|Ma tante est professeur. (Teyzem öğretmendir.)
Le cousin|Erkek kuzen|Mon cousin a dix ans. (Kuzenim on yaşında.)
La cousine|Kız kuzen|Ma cousine est très gentille. (Kuzenim çok naziktir.)
Le fils|Erkek oğul|Son fils va à l'école. (Onun oğlu okula gidiyor.)
La fille|Kız çocuk / Kız|C'est une fille intelligente. (O akıllı bir kız.)
Le bébé|Bebek|Le bébé pleure beaucoup. (Bebek çok ağlıyor.)
L'enfant|Çocuk|L'enfant joue dans le parc. (Çocuk parkta oynuyor.)
L'homme|Adam|Cet homme est très grand. (Bu adam çok uzun.)
La femme|Kadın|La femme porte une robe. (Kadın bir elbise giyiyor.)
Lundi|Pazartesi|Je travaille le lundi. (Pazartesi günü çalışıyorum.)
Mardi|Salı|Mardi, nous avons une réunion. (Salı günü bir toplantımız var.)
Mercredi|Çarşamba|Je vais au cinéma mercredi. (Çarşamba günü sinemaya gidiyorum.)
Jeudi|Perşembe|Il arrive jeudi matin. (O perşembe sabahı varıyor.)
Vendredi|Cuma|Vendredi est mon jour préféré. (Cuma en sevdiğim gündür.)
Samedi|Cumartesi|Nous faisons les courses samedi. (Cumartesi günü alışveriş yapıyoruz.)
Dimanche|Pazar|Dimanche, je me repose. (Pazar günü dinleniyorum.)
Janvier|Ocak|Il fait très froid en janvier. (Ocak ayında hava çok soğuktur.)
Février|Şubat|Mon anniversaire est en février. (Doğum günüm şubattadır.)
Mars|Mart|Le printemps commence en mars. (İlkbahar mart ayında başlar.)
Avril|Nisan|Il pleut beaucoup en avril. (Nisan ayında çok yağmur yağar.)
Le printemps|İlkbahar|Les fleurs poussent au printemps. (Çiçekler ilkbaharda büyür.)
L'été|Yaz|Nous allons à la plage en été. (Yazın plaja gideriz.)
L'automne|Sonbahar|Les feuilles tombent en automne. (Yapraklar sonbaharda düşer.)
L'hiver|Kış|J'aime la neige en hiver. (Kışın karı severim.)
La télévision|Televizyon|J'allume la télévision. (Televizyonu açıyorum.)
La radio|Radyo|J'écoute les nouvelles à la radio. (Radyoda haberleri dinliyorum.)
Le frigo|Buzdolabı|Le frigo est vide. (Buzdolabı boş.)
Le four|Fırın|Le gâteau est dans le four. (Pasta fırının içinde.)
L'assiette|Tabak|L'assiette est sur la table. (Tabak masanın üzerindedir.)
Le verre|Bardak / Cam|Je voudrais un verre d'eau. (Bir bardak su isterim.)
La fourchette|Çatal|Il mange avec une fourchette. (O bir çatalla yiyor.)
Le couteau|Bıçak|Ce couteau coupe bien. (Bu bıçak iyi kesiyor.)
La cuillère|Kaşık|Je prends une cuillère pour la soupe. (Çorba için bir kaşık alıyorum.)
Le rideau|Perde|Tire le rideau, s'il te plaît. (Lütfen perdeyi çek.)
Le tapis|Halı|Le tapis est doux. (Halı yumuşaktır.)
L'armoire|Dolap|Mes vêtements sont dans l'armoire. (Kıyafetlerim dolaptadır.)
La douche|Duş|Je prends une douche chaude. (Sıcak bir duş alıyorum.)
La serviette|Havlu|Où est ma serviette ? (Havlum nerede?)
Le savon|Sabun|Je me lave les mains avec du savon. (Ellerimi sabunla yıkıyorum.)
La route|Yol|La route est très longue. (Yol çok uzundur.)
Le pont|Köprü|Nous traversons le pont. (Köprüyü geçiyoruz.)
La place|Meydan|Il y a du monde sur la place. (Meydanda kalabalık var.)
Le bâtiment|Bina|C'est un grand bâtiment moderne. (Bu büyük ve modern bir bina.)
Le musée|Müze|Nous visitons le musée. (Müzeyi ziyaret ediyoruz.)
Le cinéma|Sinema|Le film commence au cinéma. (Film sinemada başlıyor.)
L'école|Okul|L'école finit à quatre heures. (Okul saat dörtte bitiyor.)
La banque|Banka|Je dois aller à la banque. (Bankaya gitmeliyim.)
La pharmacie|Eczane|La pharmacie est ouverte. (Eczane açıktır.)
L'aéroport|Havalimanı|L'avion atterrit à l'aéroport. (Uçak havalimanına iniyor.)
Le billet|Bilet|J'achète un billet de train. (Bir tren bileti alıyorum.)
Le passager|Yolcu|Le passager attend son vol. (Yolcu uçuşunu bekliyor.)
La valise|Bavul|Ma valise est prête. (Bavulum hazır.)
Le vol|Uçuş / Hırsızlık|Le vol est annulé. (Uçuş iptal edildi.)
Le t-shirt|Tişört|Il porte un t-shirt blanc. (O beyaz bir tişört giyiyor.)
La robe|Elbise|Sa robe est magnifique. (Onun elbisesi muhteşem.)
La jupe|Etek|Elle achète une jupe rouge. (O kırmızı bir etek satın alıyor.)
Le pull|Kazak|Mets un pull, il fait froid. (Bir kazak giy, hava soğuk.)
La veste|Ceket|C'est une belle veste en cuir. (Bu güzel bir deri ceket.)
Les chaussettes|Çoraplar|Où sont mes chaussettes ? (Çoraplarım nerede?)
Le chapeau|Şapka|Il porte un chapeau noir. (O siyah bir şapka takıyor.)
L'écharpe|Atkı|Je mets mon écharpe. (Atkımı takıyorum.)
Les gants|Eldivenler|J'ai besoin de gants en hiver. (Kışın eldivenlere ihtiyacım var.)
La ceinture|Kemer|Il achète une ceinture noire. (Siyah bir kemer satın alıyor.)
La montre|Saat (Kol saati)|Ma montre est cassée. (Saatim bozuk.)
Les lunettes|Gözlük|Il cherche ses lunettes. (Gözlüklerini arıyor.)
L'eau minérale|Maden suyu|Je préfère l'eau minérale. (Maden suyunu tercih ederim.)
Le jus|Meyve suyu|Un verre de jus d'orange, s'il vous plaît. (Bir bardak portakal suyu lütfen.)
Le thé|Çay|Nous buvons du thé noir. (Siyah çay içiyoruz.)
Le vin|Şarap|Le vin français est célèbre. (Fransız şarabı ünlüdür.)
La bière|Bira|Il commande une bière. (Bir bira sipariş ediyor.)
La soupe|Çorba|La soupe est délicieuse. (Çorba lezzetlidir.)
La salade|Salata|Je prépare une salade verte. (Yeşil bir salata hazırlıyorum.)
La pizza|Pizza|Nous mangeons une pizza ce soir. (Bu akşam pizza yiyoruz.)
Le gâteau|Pasta / Kek|C'est un gâteau au chocolat. (Bu çikolatalı bir pasta.)
Le chocolat|Çikolata|Les enfants aiment le chocolat. (Çocuklar çikolatayı sever.)
La glace|Dondurma|Je mange une glace à la vanille. (Vanilyalı dondurma yiyorum.)
Faim|Açlık|J'ai très faim. (Çok açım.)
Soif|Susuzluk|J'ai soif, donne-moi de l'eau. (Susadım, bana su ver.)
Délicieux|Lezzetli|Ce repas est délicieux. (Bu yemek lezzetli.)
Aimer|Sevmek|J'aime beaucoup ce film. (Bu filmi çok seviyorum.)
Détester|Nefret etmek|Je déteste la pluie. (Yağmurdan nefret ederim.)
Travailler|Çalışmak|Elle travaille dans un bureau. (O bir ofiste çalışıyor.)
Jouer|Oynamak|Les enfants jouent dehors. (Çocuklar dışarıda oynuyor.)
Aider|Yardım etmek|Je peux vous aider ? (Size yardım edebilir miyim?)
Changer|Değiştirmek|Je dois changer mes vêtements. (Kıyafetlerimi değiştirmeliyim.)
Commencer|Başlamak|Le cours commence à huit heures. (Ders saat sekizde başlıyor.)
Finir|Bitirmek|Je finis mon travail. (İşimi bitiriyorum.)
Choisir|Seçmek|Tu dois choisir une couleur. (Bir renk seçmelisin.)
Partir|Ayrılmak / Yola çıkmak|Nous partons demain matin. (Yarın sabah yola çıkıyoruz.)
Sortir|Çıkmak|Je veux sortir ce soir. (Bu gece dışarı çıkmak istiyorum.)
Attendre|Beklemek|J'attends le bus. (Otobüsü bekliyorum.)
Entendre|Duymak|Je n'entends rien. (Hiçbir şey duymuyorum.)
Répondre|Cevap vermek|Il ne répond pas au téléphone. (O telefona cevap vermiyor.)
Vendre|Satmak|Ils vendent leur maison. (Evlerini satıyorlar.)
Maintenant|Şimdi|Je dois partir maintenant. (Şimdi gitmeliyim.)
Bientôt|Yakında|À bientôt ! (Yakında görüşürüz!)
Tard|Geç|Il est trop tard. (Çok geç.)
L'ordinateur|Bilgisayar|L'ordinateur est sur le bureau. (Bilgisayar masanın üzerindedir.)
Le téléphone|Telefon|Mon téléphone sonne. (Telefonum çalıyor.)
L'écran|Ekran|L'écran de la télévision est grand. (Televizyonun ekranı büyüktür.)
Le clavier|Klavye|J'utilise un clavier sans fil. (Kablosuz bir klavye kullanıyorum.)
La souris|Fare (Bilgisayar)|La souris est à côté de l'ordinateur. (Fare bilgisayarın yanındadır.)
Le mot de passe|Şifre / Parola|J'ai oublié mon mot de passe. (Şifremi unuttum.)
La nature|Doğa|Il faut protéger la nature. (Doğayı korumak gerekir.)
La forêt|Orman|Nous nous promenons dans la forêt. (Ormanda yürüyüş yapıyoruz.)
La mer|Deniz|L'eau de la mer est froide. (Denizin suyu soğuk.)
Le soleil|Güneş|Le soleil brille aujourd'hui. (Bugün güneş parlıyor.)
L'étoile|Yıldız|Il y a beaucoup d'étoiles ce soir. (Bu akşam çok yıldız var.)
Le médecin|Doktor|Le médecin examine le patient. (Doktor hastayı muayene ediyor.)
L'infirmière|Hemşire|L'infirmière est très gentille. (Hemşire çok naziktir.)
L'avocat|Avukat|J'ai besoin de parler à mon avocat. (Avukatımla konuşmaya ihtiyacım var.)
Le professeur|Öğretmen|Le professeur explique la leçon. (Öğretmen dersi açıklıyor.)
Le policier|Polis|Le policier arrête la voiture. (Polis arabayı durduruyor.)
Le chien|Köpek|Le chien aboie fort ce soir. (Köpek bu akşam yüksek sesle havlıyor.)
Le chat|Kedi|Le chat dort sur le canapé. (Kedi kanepede uyuyor.)
L'oiseau|Kuş|L'oiseau chante tous les matins. (Kuş her sabah ötüyor.)
Le cheval|At|Il monte à cheval le week-end. (O hafta sonları ata biniyor.)
La vache|İnek|La vache donne du lait. (İnek süt verir.)
Le mouton|Koyun|Le mouton mange de l'herbe verte. (Koyun yeşil ot yiyor.)
La tête|Baş / Kafa|J'ai vraiment mal à la tête. (Gerçekten başım ağrıyor.)
Le bras|Kol|Il s'est cassé le bras hier. (O dün kolunu kırdı.)
La main|El|Lave-toi les mains avant le repas. (Yemekten önce ellerini yıka.)
La jambe|Bacak|Ma jambe me fait mal depuis hier. (Bacağım dünden beri ağrıyor.)
Le pied|Ayak|J'ai froid aux pieds en hiver. (Kışın ayaklarım üşüyor.)
L'œil|Göz|Il a un œil bleu et un œil vert. (Onun bir mavi, bir yeşil gözü var.)
Le nez|Burun|Mon nez coule à cause du rhume. (Nezle yüzünden burnum akıyor.)
La bouche|Ağız|Ferme la bouche quand tu manges. (Yemek yerken ağzını kapat.)
Le dos|Sırt|Mon dos est très douloureux ce matin. (Bu sabah sırtım çok ağrılı.)
Le ventre|Karın / Mide|J'ai mal au ventre, je dois m'allonger. (Karnım ağrıyor, uzanmalıyım.)
Rouge|Kırmızı|La pomme est très rouge et sucrée. (Elma çok kırmızı ve tatlı.)
Bleu|Mavi|Le ciel est bleu, sans aucun nuage. (Gökyüzü mavi, hiç bulut yok.)
Vert|Yeşil|L'herbe est plus verte au printemps. (Çimen ilkbaharda daha yeşildir.)
Jaune|Sarı|Le soleil est jaune et brillant. (Güneş sarı ve parlaktır.)
Noir|Siyah|Le chat noir me regarde fixement. (Siyah kedi bana dik dik bakıyor.)
Blanc|Beyaz|La neige est toute blanche. (Kar bembeyazdır.)
Gris|Gri|Le nuage est gris, il va pleuvoir. (Bulut gri, yağmur yağacak.)
Marron|Kahverengi|Ses yeux sont marron clair. (Gözleri açık kahverengi.)
Grand|Büyük / Uzun|C'est un très grand bâtiment. (Bu çok büyük bir bina.)
Petit|Küçük|Le petit garçon pleure dans la rue. (Küçük çocuk sokakta ağlıyor.)
Beau|Güzel / Yakışıklı|C'est un beau paysage d'automne. (Bu güzel bir sonbahar manzarası.)
Laid|Çirkin|Ce canard est particulièrement laid. (Bu ördek özellikle çirkin.)
Fort|Güçlü|Il est très fort pour soulever ça. (Bunu kaldıracak kadar çok güçlü.)
Faible|Zayıf / Güçsüz|Je me sens faible après la maladie. (Hastalıktan sonra güçsüz hissediyorum.)
Rapide|Hızlı|Ce nouveau train est très rapide. (Bu yeni tren çok hızlıdır.)
Lent|Yavaş|La tortue est un animal très lent. (Kaplumbağa çok yavaş bir hayvandır.)
Propre|Temiz|La chambre est propre et bien rangée. (Oda temiz ve düzenli.)
Sale|Kirli|Mes vêtements sont sales après le match. (Maçtan sonra kıyafetlerim kirli.)
Manger|Yemek yemek|Je veux manger une pomme maintenant. (Şimdi bir elma yemek istiyorum.)
Boire|İçmek|Il faut boire beaucoup d'eau chaque jour. (Her gün çok su içmek gerekir.)
Dormir|Uyumak|Je vais dormir tôt ce soir. (Bu akşam erken uyuyacağım.)
Parler|Konuşmak|Il parle trop vite pour moi. (O benim için çok hızlı konuşuyor.)
Écouter|Dinlemek|J'écoute la radio dans la voiture. (Arabada radyoyu dinlerim.)
Regarder|Bakmak / İzlemek|Regarde ce beau tableau sur le mur. (Duvardaki şu güzel tabloya bak.)
Voir|Görmek|Je ne vois rien dans le noir absolu. (Zifiri karanlıkta hiçbir şey görmüyorum.)
Courir|Koşmak|Il court chaque matin dans le grand parc. (Her sabah büyük parkta koşuyor.)
Marcher|Yürümek|Nous marchons ensemble vers le centre-ville. (Birlikte şehir merkezine yürüyoruz.)
Acheter|Satın almak|Je vais acheter du pain frais à la boulangerie. (Fırından taze ekmek alacağım.)
Payer|Ödemek|Je vais payer l'addition par carte de crédit. (Hesabı kredi kartıyla ödeyeceğim.)
Le vent|Rüzgar|Le vent souffle très fort aujourd'hui. (Rüzgar bugün çok sert esiyor.)
La pluie|Yağmur|La pluie tombe sans arrêt depuis hier. (Yağmur dünden beri durmadan yağıyor.)
La neige|Kar|La neige couvre toute la montagne. (Kar bütün dağı kaplıyor.)
La montagne|Dağ|Nous allons à la montagne pour faire du ski. (Kayak yapmak için dağa gidiyoruz.)
La rivière|Nehir|La rivière est très profonde ici. (Nehir burada çok derindir.)
L'arbre|Ağaç|Cet arbre au fond du jardin est très vieux. (Bahçenin sonundaki bu ağaç çok yaşlıdır.)
La fleur|Çiçek|Cette fleur rouge sent incroyablement bon. (Bu kırmızı çiçek inanılmaz güzel kokuyor.)
Le train|Tren|Le train pour Paris part à l'heure exacte. (Paris treni tam vaktinde kalkıyor.)
La voiture|Araba|Ma voiture est en panne sur l'autoroute. (Arabam otoyolda bozuldu.)
Le bus|Otobüs|Prends le bus numéro cinq pour y aller. (Oraya gitmek için beş numaralı otobüse bin.)
Le vélo|Bisiklet|J'aime faire du vélo dans la forêt. (Ormanda bisiklete binmeyi severim.)
Le bateau|Gemi / Tekne|Le bateau navigue tranquillement sur la mer. (Gemi denizde sakince seyrediyor.)
La station|İstasyon / Durak|Excusez-moi, où est la station de métro ? (Afedersiniz, metro istasyonu nerede?)
Le canapé|Kanepe|Le canapé gris du salon est très confortable. (Salondaki gri kanepe çok rahat.)
Le lit|Yatak|Le lit est défait, tu dois le faire. (Yatak dağınık, onu toplamalısın.)
La chaise|Sandalye|Prends une chaise et assieds-toi avec nous. (Bir sandalye al ve bizimle otur.)
La table|Masa|Le dîner est déjà servi sur la table. (Akşam yemeği masada çoktan servis edildi.)
La porte|Kapı|Ouvre la porte, s'il te plaît, il fait chaud. (Lütfen kapıyı aç, hava sıcak.)
La fenêtre|Pencere|Ferme la fenêtre, il fait très froid dehors. (Pencereyi kapat, dışarısı çok soğuk.)
La clé|Anahtar|J'ai perdu la clé de la maison ce matin. (Evin anahtarını bu sabah kaybettim.)
Le miroir|Ayna|Elle se regarde longtemps dans le miroir. (O aynada uzun uzun kendine bakıyor.)
Le boulanger|Fırıncı|Le boulanger prépare du bon pain croustillant. (Fırıncı güzel çıtır ekmek hazırlar.)
Le boucher|Kasap|Je vais chez le boucher pour acheter de la viande. (Et almak için kasaba gidiyorum.)
L'acteur|Aktör / Oyuncu|C'est un acteur très connu dans le monde entier. (O dünya çapında çok bilinen bir aktördür.)
Le chanteur|Şarkıcı|Ce chanteur a vraiment une belle voix. (Bu şarkıcının gerçekten güzel bir sesi var.)
L'ami|Arkadaş (Erkek)|C'est mon meilleur ami depuis l'enfance. (O çocukluktan beri en iyi arkadaşım.)
L'amie|Arkadaş (Kadın)|Mon amie habite actuellement à Lyon. (Arkadaşım şu anda Lyon'da yaşıyor.)
Le voisin|Komşu (Erkek)|Notre voisin du dessus est très bruyant. (Üst kat komşumuz çok gürültücü.)
La voisine|Komşu (Kadın)|La voisine a un chien adorable et calme. (Kadın komşunun sevimli ve sakin bir köpeği var.)
Le fromage|Peynir|La France est très célèbre pour son délicieux fromage. (Fransa lezzetli peyniriyle çok ünlüdür.)
Le poulet|Tavuk|Nous mangeons du poulet rôti ce soir. (Bu akşam fırında tavuk yiyoruz.)
Le poisson|Balık|Le poisson du marché est toujours frais. (Pazardaki balık her zaman tazedir.)
La viande|Et|Je ne mange pas beaucoup de viande rouge. (Çok fazla kırmızı et yemiyorum.)
Le pain|Ekmek|Achetons du pain frais pour le petit-déjeuner. (Kahvaltı için taze ekmek alalım.)
Le beurre|Tereyağı|Passe-moi le beurre, s'il te plaît. (Lütfen bana tereyağını uzat.)
Le sel|Tuz|La soupe de légumes manque un peu de sel. (Sebze çorbasının tuzu biraz eksik.)
Le sucre|Şeker|Je bois mon café sans aucun sucre. (Kahvemi hiç şekersiz içiyorum.)
Le trottoir|Kaldırım|Il est interdit de se garer sur le trottoir. (Kaldırıma park etmek yasaktır.)
Le feu rouge|Kırmızı ışık|Tu dois t'arrêter au feu rouge. (Kırmızı ışıkta durmalısın.)
Le carrefour|Kavşak|Tournez à gauche au prochain carrefour. (Bir sonraki kavşakta sola dönün.)
La ruelle|Sokak / Dar sokak|Cette ruelle est très sombre la nuit. (Bu dar sokak geceleri çok karanlık.)
La banlieue|Banliyö / Kenar mahalle|Ils habitent dans la banlieue de Paris. (Paris'in banliyösünde yaşıyorlar.)
Le plafond|Tavan|Le plafond de cette chambre est très haut. (Bu odanın tavanı çok yüksek.)
Le plancher|Zemin / Döşeme|Le plancher en bois grince. (Ahşap zemin gıcırdıyor.)
L'escalier|Merdiven|Fais attention en descendant l'escalier. (Merdivenden inerken dikkat et.)
Le balcon|Balkon|Je bois mon café sur le balcon. (Kahvemi balkonda içiyorum.)
La serrure|Kilit|La serrure de cette porte est cassée. (Bu kapının kilidi kırık.)
Le bureau|Ofis / Masa|Je suis au bureau jusqu'à 18h. (Saat 18'e kadar ofisteyim.)
La réunion|Toplantı|La réunion a été annulée. (Toplantı iptal edildi.)
Le patron|Patron|Mon patron est très exigeant. (Patronum çok talepkardır.)
Le collègue|Meslektaş / İş arkadaşı|Mes collègues sont très sympathiques. (İş arkadaşlarım çok cana yakın.)
L'entreprise|Şirket|Cette entreprise embauche de nouveaux ingénieurs. (Bu şirket yeni mühendisler işe alıyor.)
Le sable|Kum|Les enfants jouent dans le sable. (Çocuklar kumda oynuyor.)
La vague|Dalga|Les vagues sont très hautes aujourd'hui. (Bugün dalgalar çok yüksek.)
La pierre|Taş|Il a jeté une pierre dans le lac. (Göle bir taş attı.)
La poussière|Toz|Il y a beaucoup de poussière ici. (Burada çok toz var.)
L'ombre|Gölge|Reposons-nous à l'ombre de cet arbre. (Bu ağacın gölgesinde dinlenelim.)
Le fichier|Dosya (Bilgisayar)|N'oublie pas de sauvegarder le fichier. (Dosyayı kaydetmeyi unutma.)
Le mot de passe|Şifre / Parola|Mon mot de passe est très sécurisé. (Şifrem çok güvenlidir.)
Le chargeur|Şarj aleti|As-tu un chargeur de téléphone ? (Telefon şarj aletin var mı?)
L'écran|Ekran|L'écran de mon ordinateur est sale. (Bilgisayarımın ekranı kirli.)
Les écouteurs|Kulaklık|Je mets mes écouteurs pour écouter de la musique. (Müzik dinlemek için kulaklığımı takıyorum.)
Apprendre|Öğrenmek|J'apprends le français tous les jours. (Her gün Fransızca öğreniyorum.)
Comprendre|Anlamak|Je ne comprends pas cette phrase. (Bu cümleyi anlamıyorum.)
Oublier|Unutmak|J'ai oublié mes clés à la maison. (Anahtarlarımı evde unuttum.)
Se souvenir|Hatırlamak|Je me souviens de ce jour-là. (O günü hatırlıyorum.)
Espérer|Ummak / Ümit etmek|J'espère que tu iras mieux demain. (Umarım yarın daha iyi olursun.)
Réfléchir|Düşünmek / Kafa yormak|Je dois réfléchir avant de décider. (Karar vermeden önce düşünmeliyim.)
Gagner|Kazanmak|Notre équipe a gagné le match. (Takımımız maçı kazandı.)
Perdre|Kaybetmek|J'ai perdu mon portefeuille dans le bus. (Cüzdanımı otobüste kaybettim.)
Lourd|Ağır|Cette valise est trop lourde pour moi. (Bu bavul benim için çok ağır.)
Léger|Hafif|C'est un ordinateur très léger. (Bu çok hafif bir bilgisayar.)
Plein|Dolu|Le verre est plein d'eau. (Bardak suyla dolu.)
Vide|Boş|La rue est complètement vide ce soir. (Bu akşam sokak tamamen boş.)
Dangereux|Tehlikeli|Il est dangereux de nager ici. (Burada yüzmek tehlikelidir.)
Sécurisé|Güvenli|Ce quartier est très sécurisé. (Bu mahalle çok güvenli.)
Difficile|Zor|L'examen de mathématiques était très difficile. (Matematik sınavı çok zordu.)
Facile|Kolay|C'est une question très facile. (Bu çok kolay bir soru.)
Toujours|Her zaman|Il est toujours en retard. (O her zaman geç kalır.)
Jamais|Asla / Hiç|Je ne bois jamais de café le soir. (Akşamları asla kahve içmem.)
Parfois|Bazen|Parfois, je préfère rester seul. (Bazen yalnız kalmayı tercih ederim.)
Soudain|Aniden|Soudain, la lumière s'est éteinte. (Aniden ışık söndü.)
D'abord|Önce / İlk olarak|D'abord, nous devons trouver un hôtel. (Öncelikle bir otel bulmalıyız.)
Ensuite|Sonra / Daha sonra|Nous allons manger, et ensuite nous sortirons. (Yemek yiyeceğiz ve sonra çıkacağız.)
L'autoroute|Otoyol|Il y a beaucoup de trafic sur l'autoroute. (Otoyolda çok trafik var.)
Le vol|Uçuş|Mon vol a été annulé ce matin. (Uçuşum bu sabah iptal edildi.)
Le billet|Bilet|J'ai acheté un billet aller-retour pour Lyon. (Lyon'a gidiş-dönüş bileti aldım.)
La valise|Bavul|Ma valise est trop lourde pour moi. (Bavulum benim için çok ağır.)
Le passager|Yolcu|Le passager dort tranquillement dans l'avion. (Yolcu uçakta sakince uyuyor.)
La fourchette|Çatal|Je n'ai pas de fourchette pour manger ma salade. (Salatamı yemek için çatalım yok.)
La cuillère|Kaşık|Il boit sa soupe chaude avec une cuillère. (Sıcak çorbasını bir kaşıkla içiyor.)
Le couteau|Bıçak|Fais attention, ce couteau coupe très bien. (Dikkat et, bu bıçak çok iyi kesiyor.)
L'assiette|Tabak|J'ai cassé une assiette par accident ce matin. (Bu sabah kazara bir tabak kırdım.)
La poêle|Tava|Fais cuire les œufs dans la poêle, s'il te plaît. (Yumurtaları tavada pişir, lütfen.)
Le champignon|Mantar|J'adore manger la pizza aux champignons. (Mantarlı pizza yemeye bayılırım.)
L'oignon|Soğan|Couper des oignons me fait toujours pleurer. (Soğan doğramak beni her zaman ağlatır.)
L'ail|Sarımsak|Il y a trop d'ail dans cette sauce tomate. (Bu domates sosunda çok fazla sarımsak var.)
Heureux|Mutlu|Ils sont très heureux ensemble depuis des années. (Yıllardır birlikte çok mutlular.)
Triste|Üzgün|Elle est triste parce que son chien est malade. (Köpeği hasta olduğu için üzgün.)
Colérique|Sinirli / Öfkeli|Mon voisin est un homme très colérique. (Komşum çok öfkeli bir adamdır.)
Paresseux|Tembel|Mon chat est vraiment paresseux le dimanche. (Kedim pazar günleri gerçekten tembeldir.)
Travailleur|Çalışkan|C'est un étudiant très travailleur et intelligent. (O çok çalışkan ve zeki bir öğrencidir.)
Généreux|Cömert|Il est toujours généreux avec tous ses amis. (Bütün arkadaşlarına karşı her zaman cömerttir.)
Égoïste|Bencil|Ne sois pas si égoïste avec ta famille ! (Ailene karşı bu kadar bencil olma!)
Se réveiller|Uyanmak|Je me réveille à six heures tous les matins. (Her sabah saat altıda uyanırım.)
Se doucher|Duş almak|Je me douche immédiatement après le sport. (Spordan hemen sonra duş alırım.)
S'habiller|Giyinmek|Elle s'habille rapidement pour aller au travail. (İşe gitmek için hızlıca giyinir.)
Se brosser|Fırçalamak|N'oublie pas de te brosser les dents ce soir. (Bu akşam dişlerini fırçalamayı unutma.)
Se reposer|Dinlenmek|Je dois me reposer un peu après ce long voyage. (Bu uzun yolculuktan sonra biraz dinlenmeliyim.)
Se coucher|Yatmak / Uyumaya gitmek|Il se couche très tard le week-end. (Hafta sonları çok geç yatar.)
L'étoile|Yıldız|Il y a beaucoup d'étoiles dans le ciel ce soir. (Bu gece gökyüzünde çok yıldız var.)
La lune|Ay|La lune est pleine et brillante aujourd'hui. (Bugün ay dolunay ve parlak.)
Le nuage|Bulut|Les nuages sont gris, il va sûrement pleuvoir. (Bulutlar gri, kesinlikle yağmur yağacak.)
Le brouillard|Sis|Conduis prudemment à cause du brouillard épais. (Yoğun sis yüzünden dikkatli sür.)
L'orage|Fırtına / Gök gürültülü sağanak|J'ai très peur de l'orage depuis mon enfance. (Çocukluğumdan beri fırtınadan çok korkarım.)
L'arc-en-ciel|Gökkuşağı|Regarde ce bel arc-en-ciel après la pluie ! (Yağmurdan sonraki şu güzel gökkuşağına bak!)
La chemise|Gömlek|Il porte une chemise blanche pour sa réunion. (Toplantısı için beyaz bir gömlek giyiyor.)
Le pantalon|Pantolon|Ce pantalon noir est trop grand pour moi. (Bu siyah pantolon benim için çok büyük.)
La chaussure|Ayakkabı|Mes nouvelles chaussures sont très confortables. (Yeni ayakkabılarım çok rahat.)
La veste|Ceket|Prends ta veste, il fait vraiment froid dehors. (Ceketini al, dışarısı gerçekten soğuk.)
Le manteau|Mont / Palto|J'ai besoin d'un nouveau manteau pour l'hiver. (Kış için yeni bir paltoya ihtiyacım var.)
Le magasin|Mağaza|Ce magasin de vêtements ferme à vingt heures. (Bu giyim mağazası saat yirmide kapanır.)
La caisse|Kasa|Vous pouvez payer vos achats à la caisse. (Alışverişinizi kasada ödeyebilirsiniz.)
Cher|Pahalı|Cette robe rouge est beaucoup trop chère. (Bu kırmızı elbise çok fazla pahalı.)
Bon marché|Ucuz|J'ai trouvé un billet d'avion bon marché pour Paris. (Paris için ucuz bir uçak bileti buldum.)
Chercher|Aramak|Je cherche mes clés depuis dix minutes. (On dakikadır anahtarlarımı arıyorum.)
Trouver|Bulmak|J'ai enfin trouvé mon téléphone sous le canapé. (Sonunda telefonumu kanepenin altında buldum.)
Donner|Vermek|Peux-tu me donner ton numéro de téléphone ? (Bana telefon numaranı verebilir misin?)
Prendre|Almak|Je vais prendre un café noir, s'il vous plaît. (Bir sade kahve alacağım, lütfen.)
Aider|Yardım etmek|Il m'aide toujours avec mes devoirs de français. (Fransızca ödevlerimde bana her zaman yardım eder.)
Changer|Değiştirmek|Nous devons changer de train à la prochaine station. (Bir sonraki istasyonda tren değiştirmeliyiz.)
Hier|Dün|Je suis allé au cinéma hier avec mes amis. (Dün arkadaşlarımla sinemaya gittim.)
Aujourd'hui|Bugün|Il fait très beau aujourd'hui, allons nous promener. (Bugün hava çok güzel, yürüyüşe çıkalım.)
Demain|Yarın|Nous partirons en vacances demain matin. (Yarın sabah tatile çıkacağız.)
Le matin|Sabah|Je bois toujours du café le matin. (Sabahları her zaman kahve içerim.)
L'après-midi|Öğleden sonra|J'ai une réunion importante cet après-midi. (Bu öğleden sonra önemli bir toplantım var.)
Le soir|Akşam|Je lis un bon livre le soir avant de dormir. (Uyumadan önce akşamları iyi bir kitap okurum.)
La nuit|Gece|Il fait complètement noir pendant la nuit. (Gece boyunca hava tamamen karanlıktır.)
Chaud|Sıcak|Attention, ce thé est beaucoup trop chaud ! (Dikkat et, bu çay çok fazla sıcak!)
Froid|Soğuk|L'eau de la mer est très froide en hiver. (Kışın denizin suyu çok soğuktur.)
Nouveau|Yeni|J'ai acheté un nouvel ordinateur pour mon travail. (İşim için yeni bir bilgisayar aldım.)
Ancien|Eski|C'est un très ancien bâtiment historique. (Bu çok eski, tarihi bir bina.)
Jeune|Genç|Mon petit frère est encore très jeune. (Küçük kardeşim hala çok genç.)
Vieux|Yaşlı|Ce vieil homme est mon grand-père paternel. (Bu yaşlı adam benim baba tarafından büyükbabamdır.)
Riche|Zengin|Il est devenu riche grâce à son entreprise. (Şirketi sayesinde zengin oldu.)
Pauvre|Fakir|Il faut toujours aider les personnes pauvres. (Fakir insanlara her zaman yardım etmek gerekir.)
Le cœur|Kalp|Le cœur pompe le sang dans tout le corps. (Kalp, kanı tüm vücuda pompalar.)
L'hôpital|Hastane|Il travaille à l'hôpital comme infirmier. (Hastanede hemşire olarak çalışıyor.)
La pharmacie|Eczane|La pharmacie de garde est ouverte toute la nuit. (Nöbetçi eczane bütün gece açık.)
L'ingénieur|Mühendis|L'ingénieur dessine les plans du nouveau pont. (Mühendis yeni köprünün planlarını çiziyor.)
Le juge|Hakim|Le juge prendra sa décision finale demain. (Hakim son kararını yarın verecek.)
Le pompier|İtfaiyeci|Le pompier a courageusement sauvé le chat de l'arbre. (İtfaiyeci cesurca kediyi ağaçtan kurtardı.)
Le pilote|Pilot|Le pilote annonce le départ imminent de l'avion. (Pilot uçağın birazdan kalkacağını anons ediyor.)
Le métro|Metro|Je prends le métro tous les jours pour aller au travail. (İşe gitmek için her gün metroyu kullanıyorum.)
L'avion|Uçak|L'avion vole tranquillement au-dessus des nuages. (Uçak bulutların üzerinde sakince uçuyor.)
La gare|Tren istasyonu|La gare est située en plein centre-ville. (Tren istasyonu tam şehir merkezinde yer alıyor.)
Le stylo|Kalem|As-tu un stylo à me prêter pour signer ça ? (Bunu imzalamam için bana ödünç verecek bir kalemin var mı?)
Le livre|Kitap|Ce livre raconte une histoire fascinante. (Bu kitap büyüleyici bir hikaye anlatıyor.)
Lire|Okumak|J'aime lire des romans d'aventure pendant mon temps libre. (Boş zamanlarımda macera romanları okumayı severim.)
Écrire|Yazmak|Il écrit une longue lettre à son ami d'enfance. (Çocukluk arkadaşına uzun bir mektup yazıyor.)
Ouvrir|Açmak|Pouvez-vous ouvrir la fenêtre, s'il vous plaît ? (Pencereyi açabilir misiniz, lütfen?)
Fermer|Kapatmak|N'oublie pas de fermer la porte en sortant. (Çıkarken kapıyı kapatmayı unutma.)
Pleurer|Ağlamak|Le bébé commence à pleurer parce qu'il a faim. (Bebek aç olduğu için ağlamaya başlıyor.)
Rire|Gülmek|Cette blague me fait toujours rire aux éclats. (Bu şaka beni her zaman kahkahalarla güldürür.)
Sourire|Gülümsemek|Elle a l'habitude de sourire aux inconnus. (O, yabancılara gülümseme alışkanlığına sahiptir.)
Demander|Sormak / İstemek|Je dois demander l'heure à quelqu'un dans la rue. (Sokakta birine saati sormalıyım.)
Répondre|Cevap vermek|Il n'a pas voulu répondre à ma question personnelle. (Benim kişisel soruma cevap vermek istemedi.)
Savoir|Bilmek|Je ne sais pas du tout comment faire ça. (Bunu nasıl yapacağımı hiç bilmiyorum.)
Connaître|Tanımak / Bilmek (Bir yeri/kişiyi)|Connaissez-vous ce célèbre écrivain français ? (Bu ünlü Fransız yazarı tanıyor musunuz?)
Attendre|Beklemek|J'attends le bus depuis plus de vingt minutes. (Yirmi dakikadan fazladır otobüsü bekliyorum.)
Vivre|Yaşamak|Ils veulent vivre à la campagne, loin du bruit. (Gürültüden uzak, kırsalda yaşamak istiyorlar.)
Sympathique|Sempatik / Cana yakın|Elle est très sympathique avec tout le monde. (O herkese karşı çok cana yakındır.)
Antipathique|İtici / Sevimsiz|Ce vendeur était vraiment antipathique aujourd'hui. (Bu satıcı bugün gerçekten çok iticiydi.)
Bavard|Konuşkan / Geveze|Mon nouveau voisin est très bavard. (Yeni komşum çok konuşkandır.)
Silencieux|Sessiz|C'est un garçon très silencieux et calme. (O çok sessiz ve sakin bir çocuktur.)
Courageux|Cesur|Le pompier est un homme très courageux. (İtfaiyeci çok cesur bir adamdır.)
Lâche|Korkak|Il a été lâche de fuir le problème. (Problemden kaçarak korkaklık yaptı.)
Fier|Gururlu|Je suis fier de tes excellents résultats. (Senin mükemmel sonuçlarınla gurur duyuyorum.)
Honnête|Dürüst|Il faut toujours être honnête avec soi-même. (İnsan her zaman kendine karşı dürüst olmalıdır.)
Menteur|Yalancı|Ne fais surtout pas confiance à ce menteur. (Bu yalancıya sakın güvenme.)
Le passeport|Pasaport|N'oublie pas ton passeport pour le voyage. (Yolculuk için pasaportunu unutma.)
La douane|Gümrük|Nous avons passé la douane sans aucun problème. (Gümrükten hiçbir sorun olmadan geçtik.)
Le quai|Peron / İskele|Le train pour Marseille part du quai numéro quatre. (Marsilya treni dört numaralı perondan kalkıyor.)
Le trajet|Yolculuk / Güzergah|Le trajet jusqu'à l'hôtel est très court. (Otele kadar olan güzergah çok kısadır.)
La frontière|Sınır|Nous venons de traverser la frontière espagnole. (İspanya sınırını az önce geçtik.)
La colline|Tepe|Il y a un très beau château sur la colline. (Tepede çok güzel bir şato var.)
La vallée|Vadi|Ce petit village est situé dans une grande vallée. (Bu küçük köy büyük bir vadide yer almaktadır.)
Le fleuve|Nehir (Denize dökülen)|La Seine est un fleuve très célèbre en France. (Seine, Fransa'da çok ünlü bir nehirdir.)
Le lac|Göl|Nous allons nager dans le lac cet après-midi. (Bu öğleden sonra gölde yüzeceğiz.)
La forêt|Orman|J'aime me promener dans la forêt en automne. (Sonbaharda ormanda yürüyüş yapmayı severim.)
La plage|Plaj / Kumsal|Les enfants jouent tranquillement sur la plage. (Çocuklar kumsalda sakince oynuyor.)
L'île|Ada|Ils ont passé leurs vacances sur une île tropicale. (Tatillerini tropikal bir adada geçirdiler.)
Accepter|Kabul etmek|J'ai décidé d'accepter cette offre d'emploi. (Bu iş teklifini kabul etmeye karar verdim.)
Refuser|Reddetmek|Il a refusé de m'aider avec mes bagages. (Bavullarımla bana yardım etmeyi reddetti.)
Crier|Bağırmak|Ne crie pas, je t'entends très bien d'ici. (Bağırma, seni buradan gayet iyi duyuyorum.)
Chuchoter|Fısıldamak|Il chuchote pour ne pas réveiller l'enfant qui dort. (Uyuyan çocuğu uyandırmamak için fısıldıyor.)
Avant|Önce|Lave-toi les mains avant le dîner. (Akşam yemeğinden önce ellerini yıka.)
Après|Sonra|Que vas-tu faire après ton travail ce soir ? (Bu akşam işinden sonra ne yapacaksın?)
Pendant|Sırasında / Boyunca|Je n'ai pas parlé pendant tout le film. (Bütün film boyunca konuşmadım.)
Derrière|Arkasında|Le petit chat se cache derrière le canapé. (Küçük kedi kanepenin arkasına saklanıyor.)
Devant|Önünde|Il y a une belle voiture garée devant la maison. (Evin önünde park etmiş güzel bir araba var.)
Sous|Altında|Tes chaussures de sport sont sous le lit. (Spor ayakkabıların yatağın altında.)
Sur|Üzerinde|Le dictionnaire de français est sur la table. (Fransızca sözlük masanın üzerinde.)
Entre|Arasında|Mon bureau est entre la banque et la poste. (Ofisim banka ile postane arasındadır.)
Contre|Karşı / Karşısında|Il est fatigué, il est appuyé contre le mur. (Yorgun, duvara yaslanmış.)
Avec|İle / Birlikte|Je veux vraiment aller au cinéma avec toi. (Seninle gerçekten sinemaya gitmek istiyorum.)
Sans|Olmadan / -sız|Je bois toujours mon café sans sucre le matin. (Sabahları kahvemi her zaman şekersiz içerim.)
Déjà|Zaten / Çoktan|J'ai déjà fini tout mon travail aujourd'hui. (Bugün bütün işimi çoktan bitirdim.)
Encore|Hala / Tekrar|Il pleut encore ce matin, prends ton parapluie. (Bu sabah hala yağmur yağıyor, şemsiyeni al.)
Souvent|Sık sık|Nous allons souvent à ce petit restaurant italien. (Bu küçük İtalyan restoranına sık sık gideriz.)
Rarement|Nadiren|Elle mange rarement de la viande rouge. (O nadiren kırmızı et yer.)
Bizarre|Tuhaf / Garip|Ce bruit venant du moteur est vraiment bizarre. (Motordan gelen bu ses gerçekten tuhaf.)
Horrible|Korkunç|Le temps est horrible aujourd'hui, restons à l'intérieur. (Bugün hava korkunç, içeride kalalım.)
Merveilleux|Harika / Mükemmel|C'est un paysage merveilleux, prenons une photo. (Bu harika bir manzara, bir fotoğraf çekelim.)
Le supermarché|Süpermarket|Je vais au supermarché pour faire les courses de la semaine. (Haftanın alışverişini yapmak için süpermarkete gidiyorum.)
L'ascenseur|Asansör|L'ascenseur est en panne, nous devons utiliser les escaliers. (Asansör bozuk, merdivenleri kullanmalıyız.)
Le cou|Boyun|J'ai très mal au cou à cause de mon oreiller. (Yastığım yüzünden boynum çok ağrıyor.)
Le genou|Diz|Il s'est blessé au genou pendant le match de football. (Futbol maçı sırasında dizinden yaralandı.)
L'épaule|Omuz|Elle a porté un sac très lourd sur son épaule. (Omuzunda çok ağır bir çanta taşıdı.)
Le portefeuille|Cüzdan|J'ai oublié mon portefeuille dans la voiture de mon ami. (Cüzdanımı arkadaşımın arabasında unuttum.)
La monnaie|Bozuk para / Para üstü|Avez-vous de la monnaie pour la machine à café ? (Kahve makinesi için bozuk paranız var mı?)
Le billet|Kağıt para / Bilet|Il m'a donné un billet de dix euros. (Bana on euroluk bir kağıt para verdi.)
Réussir|Başarmak|Je suis sûr que tu vas réussir cet examen difficile. (Bu zor sınavı başaracağına eminim.)
Échouer|Başarısız olmak / Kalmak|Il a échoué à son permis de conduire pour la deuxième fois. (Ehliyet sınavında ikinci kez başarısız oldu.)
Penser|Düşünmek|Je pense que c'est une très bonne idée pour le projet. (Bunun proje için çok iyi bir fikir olduğunu düşünüyorum.)
Créer|Yaratmak / Oluşturmak|Cet artiste aime créer des choses totalement nouvelles. (Bu sanatçı tamamen yeni şeyler yaratmayı sever.)
Appeler|Aramak / Çağırmak|Je vais appeler mon ami ce soir pour son anniversaire. (Doğum günü için bu akşam arkadaşımı arayacağım.)
Rapide|Hızlı|Ce nouveau train est extrêmement rapide. (Bu yeni tren son derece hızlıdır.)
Lent|Yavaş|La tortue est un animal très lent mais patient. (Kaplumbağa çok yavaş ama sabırlı bir hayvandır.)
Fort|Güçlü|Il faut être fort pour soulever cette grande boîte. (Bu büyük kutuyu kaldırmak için güçlü olmak gerekir.)
Faible|Zayıf / Güçsüz|Je me sens faible après cette longue maladie d'hiver. (Bu uzun kış hastalığından sonra kendimi güçsüz hissediyorum.)
Propre|Temiz|La chambre d'hôtel est très propre et bien rangée. (Otel odası çok temiz ve düzenli.)
Sale|Kirli / Pis|Tes chaussures sont sales, enlève-les avant d'entrer. (Ayakkabıların kirli, girmeden önce onları çıkar.)
La poubelle|Çöp kutusu|Jette cette bouteille en plastique dans la poubelle. (Bu plastik şişeyi çöp kutusuna at.)
Le miroir|Ayna|Elle se regarde longtemps dans le grand miroir du salon. (Salondaki büyük aynada uzun uzun kendine bakıyor.)
Le savon|Sabun|Lave-toi bien les mains avec du savon liquide. (Ellerini sıvı sabunla iyice yıka.)
La serviette|Havlu|Peux-tu m'apporter une serviette propre, s'il te plaît ? (Bana temiz bir havlu getirebilir misin, lütfen?)
Le toit|Çatı|Le chat noir dort souvent sur le toit de la maison. (Siyah kedi sık sık evin çatısında uyur.)
Le mur|Duvar|Le mur de cette grande chambre est peint en blanc. (Bu büyük odanın duvarı beyaza boyanmış.)
La clé|Anahtar|J'ai malheureusement perdu la clé de mon appartement. (Maalesef dairemin anahtarını kaybettim.)
Le quartier|Mahalle / Semt|J'habite dans un quartier très calme et sécurisé. (Çok sakin ve güvenli bir mahallede yaşıyorum.)
Prêt|Hazır|Êtes-vous prêt pour cette nouvelle aventure ? (Bu yeni macera için hazır mısınız?)
Le rond-point|Kavşak / Döner kavşak|Prenez la deuxième sortie au rond-point. (Döner kavşakta ikinci çıkıştan çıkın.)
Le piéton|Yaya|Il faut toujours s'arrêter pour laisser passer un piéton. (Bir yayanın geçmesine izin vermek için her zaman durmak gerekir.)
La circulation|Trafik / Akış|La circulation est très fluide ce matin. (Bu sabah trafik çok akıcı.)
L'embouteillage|Trafik sıkışıklığı|Je suis en retard à cause d'un énorme embouteillage. (Büyük bir trafik sıkışıklığı yüzünden geç kaldım.)
Le loyer|Kira|Le loyer de cet appartement est beaucoup trop cher. (Bu dairenin kirası çok fazla pahalı.)
Le propriétaire|Ev sahibi / Mülk sahibi|Le propriétaire veut vendre cette maison l'année prochaine. (Ev sahibi bu evi gelecek yıl satmak istiyor.)
Le locataire|Kiracı|Le nouveau locataire arrivera à la fin du mois. (Yeni kiracı ay sonunda gelecek.)
Le chauffage|Isıtma / Kalorifer|Le chauffage ne fonctionne pas, il fait très froid ici. (Kalorifer çalışmıyor, burası çok soğuk.)
La climatisation|Klima|Peux-tu allumer la climatisation, s'il te plaît ? (Klimayı açabilir misin, lütfen?)
La recette|Tarif (Yemek)|J'ai trouvé une excellente recette de gâteau au chocolat. (Harika bir çikolatalı pasta tarifi buldum.)
La boisson|İçecek|Quelle est ta boisson préférée en été ? (Yazın en sevdiğin içecek nedir?)
L'entrée|Başlangıç yemeği|Comme entrée, je voudrais une petite salade verte. (Başlangıç olarak küçük bir yeşil salata istiyorum.)
Le plat principal|Ana yemek|Le plat principal sera servi dans quelques minutes. (Ana yemek birkaç dakika içinde servis edilecek.)
Le dessert|Tatlı|Je n'ai plus faim pour le dessert. (Tatlı için artık aç değilim.)
Fade|Tatsız / Yavan|Cette soupe est un peu fade, il manque du sel. (Bu çorba biraz tatsız, tuzu eksik.)
Épicé|Baharatlı / Acı|Je ne peux pas manger ce plat car il est trop épicé. (Bu yemeği yiyemem çünkü çok baharatlı.)
Pardonner|Affetmek|C'est très difficile de pardonner une telle erreur. (Böyle bir hatayı affetmek çok zor.)
Remercier|Teşekkür etmek|Je tiens à vous remercier pour votre aide précieuse. (Değerli yardımınız için size teşekkür etmek isterim.)
Féliciter|Tebrik etmek|Nous voulons vous féliciter pour votre nouveau travail. (Yeni işiniz için sizi tebrik etmek istiyoruz.)
S'excuser|Özür dilemek|Il s'est excusé pour son comportement impoli hier soir. (Dün akşamki kaba davranışı için özür diledi.)
S'inquiéter|Endişelenmek|Ne t'inquiète pas, tout va bien se passer. (Endişelenme, her şey yolunda gidecek.)
Se plaindre|Şikayet etmek|Il passe son temps à se plaindre de son travail. (Zamanını işinden şikayet ederek geçiriyor.)
S'habituer|Alışmak|Je n'arrive pas à m'habituer à ce nouveau climat. (Bu yeni iklime bir türlü alışamıyorum.)
Célèbre|Ünlü / Meşhur|C'est un acteur très célèbre en France et en Europe. (O Fransa'da ve Avrupa'da çok ünlü bir aktördür.)
Inconnu|Bilinmeyen / Tanınmayan|Cet artiste est encore complètement inconnu du grand public. (Bu sanatçı hala halk tarafından tamamen bilinmiyor.)
Pratique|Kullanışlı / Pratik|Cette application est vraiment pratique pour apprendre des langues. (Bu uygulama dil öğrenmek için gerçekten çok kullanışlı.)
Inutile|İşe yaramaz / Gereksiz|C'est complètement inutile de crier, reste calme. (Bağırmak tamamen gereksiz, sakin ol.)
Récemment|Son zamanlarda / Geçenlerde|J'ai vu un très bon film français récemment. (Geçenlerde çok iyi bir Fransız filmi izledim.)
Quelquefois|Bazen / Ara sıra|Quelquefois, je préfère rester seul pour réfléchir. (Bazen düşünmek için yalnız kalmayı tercih ederim.)
Presque|Neredeyse / Hemen hemen|J'ai presque fini mon travail, donne-moi cinq minutes. (İşimi neredeyse bitirdim, bana beş dakika ver.)
Environ|Yaklaşık / Civarında|Le trajet dure environ deux heures en voiture. (Yolculuk arabayla yaklaşık iki saat sürüyor.)
D'habitude|Genellikle / Adet olduğu üzere|D'habitude, je me réveille très tôt le matin. (Genellikle sabahları çok erken uyanırım.)
Peut-être|Belki|Il viendra peut-être nous voir ce week-end. (Belki bu hafta sonu bizi görmeye gelir.)
Heureusement|Neyse ki / Çok şükür|Heureusement, personne n'a été blessé dans l'accident. (Neyse ki kazada kimse yaralanmadı.)
Malheureusement|Maalesef|Malheureusement, nous n'avons plus de billets disponibles. (Maalesef artık müsait biletimiz yok.)
La vérité|Gerçek / Doğru|Il faut toujours dire la vérité, même si c'est dur. (Zor olsa bile her zaman doğruyu söylemek gerekir.)
Le mensonge|Yalan|Je déteste le mensonge, sois honnête avec moi. (Yalandan nefret ederim, bana karşı dürüst ol.)
L'objectif|Hedef / Amaç|Mon objectif principal est d'apprendre le français. (Temel hedefim Fransızca öğrenmek.)
Le défi|Meydan okuma / Zorluk|C'est un grand défi pour notre équipe. (Bu, takımımız için büyük bir zorluk/meydan okuma.)
L'avantage|Avantaj|Le grand avantage de cette ville est son climat. (Bu şehrin büyük avantajı iklimidir.)
L'inconvénient|Dezavantaj|Le seul inconvénient est le prix élevé. (Tek dezavantajı yüksek fiyattır.)
Le comportement|Davranış|Son comportement en classe est inacceptable. (Sınıftaki davranışı kabul edilemez.)
L'habitude|Alışkanlık|Il a la mauvaise habitude de fumer. (Onun kötü bir sigara içme alışkanlığı var.)
Le rendez-vous|Randevu / Buluşma|J'ai un rendez-vous chez le médecin à 15h. (Saat 15'te doktorda randevum var.)
L'emploi du temps|Program / Çalışma takvimi|Mon emploi du temps est très chargé cette semaine. (Bu hafta programım çok yoğun.)
Le congé|İzin (İş/Okul)|Il a pris quelques jours de congé pour se reposer. (Dinlenmek için birkaç gün izin aldı.)
Le salaire|Maaş|Son nouveau salaire est très motivant. (Yeni maaşı çok motive edici.)
S'améliorer|Gelişmek / İyileşmek|Ton français s'améliore de jour en jour. (Fransızcan günden güne gelişiyor.)
Se concentrer|Odaklanmak|Il est difficile de se concentrer avec tout ce bruit. (Bu kadar gürültüyle odaklanmak çok zor.)
Se dépêcher|Acele etmek|Nous devons nous dépêcher, le train va partir. (Acele etmeliyiz, tren kalkacak.)
S'ennuyer|Sıkılmak|Les enfants s'ennuient pendant les longues vacances. (Çocuklar uzun tatillerde sıkılırlar.)
Se tromper|Yanılmak / Hata yapmak|Je crois que tu t'es trompé de numéro. (Sanırım numarayı yanlış girdin / yanıldın.)
Se rappeler|Hatırlamak|Je ne me rappelle pas de son nom de famille. (Onun soyadını hatırlamıyorum.)
Évidemment|Elbette / Belli ki|Évidemment, je viendrai à ton mariage ! (Elbette düğününe geleceğim!)
Probablement|Muhtemelen|Il sera probablement en retard à cause de la pluie. (Yağmur yüzünden muhtemelen geç kalacak.)
Absolument|Kesinlikle|Tu as absolument raison sur toute la ligne. (Baştan sona kesinlikle haklısın.)
Doucement|Yavaşça / Nazikçe|Parlez doucement, le bébé dort dans la chambre. (Yavaşça konuşun, bebek odada uyuyor.)
Vraiment|Gerçekten|Ce gâteau au chocolat est vraiment délicieux. (Bu çikolatalı pasta gerçekten lezzetli.)
Étonnant|Şaşırtıcı|C'est étonnant qu'il ne soit pas encore arrivé. (Hala gelmemiş olması şaşırtıcı.)
Décevant|Hayal kırıklığı yaratan|La fin de ce film était très décevante. (Bu filmin sonu çok hayal kırıklığı yarattı.)
Passionnant|Heyecan verici / Büyüleyici|Ce livre raconte une histoire passionnante. (Bu kitap büyüleyici bir hikaye anlatıyor.)
Ennuyeux|Sıkıcı|Ce cours d'histoire est incroyablement ennuyeux. (Bu tarih dersi inanılmaz derecede sıkıcı.)
Épuisé|Tükenmiş / Çok yorgun|Je suis complètement épuisé après ce long voyage. (Bu uzun yolculuktan sonra tamamen tükendim.)
La douleur|Ağrı / Acı|Il ressent une forte douleur dans le dos. (Sırtında şiddetli bir ağrı hissediyor.)
Le remède|Çare / İlaç|Le meilleur remède contre le stress est le repos. (Strese karşı en iyi ilaç dinlenmektir.)
La santé|Sağlık|La santé est la chose la plus importante dans la vie. (Sağlık hayattaki en önemli şeydir.)
Le conseil|Tavsiye / Öğüt|Puis-je te donner un petit conseil d'ami ? (Sana küçük bir dost tavsiyesi verebilir miyim?)
L'erreur|Hata|Tout le monde fait des erreurs, c'est normal. (Herkes hata yapar, bu normaldir.)
La solution|Çözüm|Nous devons trouver une solution à ce grave problème. (Bu ciddi soruna bir çözüm bulmalıyız.)
Le choix|Seçim / Tercih|Tu as le choix entre le thé et le café. (Çay ve kahve arasında seçim yapabilirsin/seçeneğin var.)
Le chômage|İşsizlik|Le taux de chômage a diminué cette année. (İşsizlik oranı bu yıl azaldı.)
L'expérience|Deneyim / Tecrübe|Avez-vous de l'expérience dans ce domaine ? (Bu alanda deneyiminiz var mı?)
La compétence|Yetenek / Beceri|La communication est une compétence importante. (İletişim önemli bir beceridir.)
Licencier|İşten çıkarmak|L'entreprise a dû licencier plusieurs employés. (Şirket birkaç çalışanı işten çıkarmak zorunda kaldı.)
Le poste|Pozisyon / Makam|Ce poste demande beaucoup de responsabilités. (Bu pozisyon çok fazla sorumluluk gerektiriyor.)
L'augmentation|Maaş artışı / Zam|Il a demandé une augmentation à son patron. (Patronundan maaş artışı/zam istedi.)
Le clavier|Klavye|J'ai renversé du café sur mon clavier d'ordinateur. (Bilgisayar klavyemin üzerine kahve döktüm.)
La souris|Fare (Bilgisayar)|La souris sans fil de mon bureau ne fonctionne plus. (Ofisimdeki kablosuz fare artık çalışmıyor.)
Imprimer|Yazdırmak / Çıktı almak|Je dois imprimer ces documents pour la réunion. (Toplantı için bu belgelerin çıktısını almalıyım.)
Supprimer|Silmek|N'oublie pas de supprimer ce fichier inutile. (Bu gereksiz dosyayı silmeyi unutma.)
Partager|Paylaşmak|Il a partagé une belle photo sur les réseaux sociaux. (Sosyal ağlarda güzel bir fotoğraf paylaştı.)
La réception|Resepsiyon|La clé de votre chambre est disponible à la réception. (Odanızın anahtarı resepsiyonda mevcuttur.)
Compris|Dahil|Le petit-déjeuner est bien compris dans le prix de la chambre. (Kahvaltı, oda fiyatına elbette dahildir.)
Libre|Boş / Müsait|Avez-vous une chambre libre pour ce soir ? (Bu akşam için boş bir odanız var mı?)
La plainte|Şikayet|Je voudrais faire une plainte concernant le bruit. (Gürültüyle ilgili bir şikayette bulunmak istiyorum.)
Réserver|Rezervasyon yapmak|J'ai appelé le restaurant pour réserver une table pour deux. (İki kişilik bir masa rezervasyonu yapmak için restoranı aradım.)
Doux|Ilıman / Yumuşak / Tatlı|Le climat est très doux dans cette région du sud. (Güneydeki bu bölgede iklim çok ılımandır.)
Humide|Nemli|L'air est très humide juste après la forte pluie. (Şiddetli yağmurun hemen ardından hava çok nemli.)
Geler|Donmak|L'eau du lac commence à geler en hiver. (Kışın gölün suyu donmaya başlar.)
La tempête|Fırtına|La tempête de cette nuit a causé beaucoup de dégâts. (Bu geceki fırtına çok fazla hasara neden oldu.)
Dégoûtant|İğrenç|Ce plat au restaurant a une odeur vraiment dégoûtante. (Restorandaki bu yemeğin gerçekten iğrenç bir kokusu var.)
Mignon|Sevimli / Tatlı|Ton petit chat blanc est vraiment très mignon. (Küçük beyaz kedin gerçekten çok sevimli.)
Grave|Ciddi / Ağır|Heureusement, sa blessure à la jambe n'est pas grave. (Neyse ki bacağındaki yarası ciddi değil.)
Bavarder|Sohbet etmek|Elles aiment bavarder au café pendant des heures. (Kafede saatlerce sohbet etmeyi severler.)
Se taire|Susmak|Il a préféré se taire pendant la longue dispute. (Uzun tartışma sırasında susmayı tercih etti.)
S'adapter|Uyum sağlamak|Il est facile de s'adapter à la vie de cette nouvelle ville. (Bu yeni şehrin hayatına uyum sağlamak kolaydır.)
Sauf|Hariç / Dışında|Tout le monde est venu à la fête sauf Marc. (Marc hariç herkes partiye geldi.)
Selon|Göre (-e göre)|Selon la météo, il va pleuvoir toute la journée demain. (Hava durumuna göre yarın bütün gün yağmur yağacak.)
Malgré|Rağmen (-e rağmen)|Nous sommes sortis nous promener malgré le mauvais temps. (Kötü havaya rağmen yürüyüşe çıktık.)
Tandis que|İken / Halbuki|Il lit tranquillement, tandis que je regarde la télévision. (Ben televizyon izlerken o sakince okuyor.)
Afin de|Amacıyla (-mek için)|Je m'entraîne tous les jours afin de gagner la course. (Yarışı kazanmak amacıyla her gün antrenman yapıyorum.)
Depuis|Beridir (-den beri)|J'habite dans ce petit quartier depuis cinq ans. (Beş yıldan beri bu küçük mahallede yaşıyorum.)
Pourtant|Oysaki / Yine de|Il a beaucoup étudié, pourtant il a raté son examen. (Çok çalıştı, oysaki sınavında başarısız oldu.)
Au lieu de|Yerine (-in yerine)|Au lieu de pleurer, tu devrais chercher une solution. (Ağlamak yerine bir çözüm aramalısın.)
Ensuite|Sonrasında|Nous allons manger, et ensuite nous irons dormir. (Yemek yiyeceğiz ve sonrasında uyumaya gideceğiz.)
`;
